//! M1 known-answer tests: every table FONTCORE parses, checked against fontTools' reading of the same
//! files (tests/data/kat_data.rs, generated by oracle/gen_kat.py). A font that is missing or differs is skipped
//! with a note, never silently passed: the test fails if NO font could be checked.

mod common;
#[path = "data/kat_data.rs"]
mod kat_data;

use font_core::{Font, Outlines};
use kat_data::KATS;

#[test]
fn tables_match_fonttools() {
    let mut checked = 0;
    let mut n_cmap = 0;
    let mut n_outline = 0;
    let mut n_comp = 0;
    let mut n_kern = 0;
    for k in KATS {
        let Some(data) = common::load(k.path, Some(k.sha256)) else { continue };
        let f = Font::parse(&data).unwrap_or_else(|e| panic!("{}: {e:?}", k.path));
        assert_eq!(f.num_glyphs, k.num_glyphs, "{} numGlyphs", k.path);
        assert_eq!(f.units_per_em, k.upem, "{} upem", k.path);
        assert_eq!([f.ascender, f.descender, f.line_gap], k.hhea, "{} hhea", k.path);
        let o = f.os2.expect("OS/2");
        assert_eq!([o.typo_ascender, o.typo_descender, o.typo_line_gap], k.typo, "{} typo", k.path);
        assert_eq!([o.win_ascent, o.win_descent], k.win, "{} win", k.path);
        assert_eq!(o.x_height.unwrap_or(0), k.x_height, "{} xHeight", k.path);
        assert_eq!(o.cap_height.unwrap_or(0), k.cap_height, "{} capHeight", k.path);
        assert_eq!(o.weight_class, k.weight, "{} weight", k.path);
        let p = f.post.expect("post");
        assert_eq!(p.italic_angle, k.italic_angle, "{} italicAngle", k.path);
        assert_eq!([p.underline_position, p.underline_thickness], k.underline, "{} underline", k.path);
        assert_eq!(p.is_fixed_pitch, k.fixed_pitch, "{} isFixedPitch", k.path);
        assert_eq!(matches!(f.outlines, Outlines::Cff(_)), k.is_cff, "{} outline kind", k.path);
        // Advance widths of a–z.
        let adv: Vec<u16> = ('a'..='z').map(|c| f.advance(f.glyph_index(c))).collect();
        assert_eq!(adv.as_slice(), &k.advances_az, "{} a-z advances", k.path);
        // cmap over 200 code points (mapped and unmapped).
        for &(cp, g) in k.cmap {
            assert_eq!(f.glyph_index(char::from_u32(cp).unwrap()), g, "{} cmap U+{cp:04X}", k.path);
            n_cmap += 1;
        }
        // Outlines: contour count, exact control box, signed area.
        for ol in k.outlines {
            let gid = f.glyph_index(ol.ch);
            assert_eq!(gid, ol.glyph, "{} '{}' gid", k.path, ol.ch);
            let path = f.glyph_path(gid).unwrap_or_else(|| panic!("{} '{}' outline", k.path, ol.ch));
            assert_eq!(path.contours(), ol.contours, "{} '{}' contours", k.path, ol.ch);
            let cb = [path.x_min as f64, path.y_min as f64, path.x_max as f64, path.y_max as f64];
            for i in 0..4 {
                assert!((cb[i] - ol.cbox[i]).abs() < 1e-3, "{} '{}' cbox {cb:?} vs {:?}", k.path, ol.ch, ol.cbox);
            }
            let a = common::signed_area(&path.cmds);
            let tol = 1e-4 * ol.area.abs().max(1.0);
            assert!((a - ol.area).abs() <= tol, "{} '{}' area {a} vs {}", k.path, ol.ch, ol.area);
            n_outline += 1;
        }
        // Composite components.
        if let Outlines::Glyf(g) = f.outlines {
            for c in k.composites {
                let comps = g.components(c.glyph).unwrap();
                assert_eq!(comps.len(), c.comps.len(), "{} {} component count", k.path, c.name);
                for (got, want) in comps.iter().zip(c.comps) {
                    assert_eq!((got.glyph, got.arg1, got.arg2), (want.glyph, want.dx, want.dy), "{} {}", k.path, c.name);
                }
                assert!(f.glyph_path(c.glyph).is_some(), "{} {} composite outline", k.path, c.name);
                n_comp += 1;
            }
        }
        // post glyph names.
        for &(gid, name) in k.names {
            assert_eq!(f.glyph_name(gid).as_deref(), Some(name), "{} name of {gid}", k.path);
        }
        // Legacy kern pairs.
        if let Some(kt) = f.kern {
            assert_eq!(kt.pair_count(), k.kern_count, "{} kern pair count", k.path);
            for &(a, b, v) in k.kern_pairs {
                assert_eq!(kt.pair(a, b), v, "{} kern {a} {b}", k.path);
                n_kern += 1;
            }
        }
        // CFF: every charstring's own width equals fontTools' Type 2 interpreter's.
        if let Outlines::Cff(c) = f.outlines {
            assert_eq!(k.cff_widths.len(), f.num_glyphs as usize);
            for gid in 0..f.num_glyphs {
                let mut p = font_core::Path::new();
                let w = c.outline(gid, &mut p).unwrap_or_else(|| panic!("{} glyph {gid}", k.path));
                assert_eq!(w, k.cff_widths[gid as usize], "{} charstring width of {gid}", k.path);
            }
        }
        // Every glyph's outline must load (no malformed glyph in a shipping font).
        for gid in 0..f.num_glyphs {
            let mut p = font_core::Path::new();
            assert!(f.outline(gid, &mut p), "{} glyph {gid} failed to load", k.path);
        }
        checked += 1;
    }
    eprintln!("KAT: {checked} fonts, {n_cmap} cmap lookups, {n_outline} outlines, {n_comp} composites, {n_kern} kern pairs");
    assert!(checked > 0, "no KAT font available on this host");
}

#[test]
fn cmap_subtable_formats_agree() {
    // DejaVu Sans carries format 4 (3,1), format 6 (1,0) and format 12 (3,10): every BMP mapping of the
    // format-4 table must be repeated by the format-12 table, and format 6 must agree on ASCII letters.
    let Some(data) = common::load("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", None) else { return };
    let f = Font::parse(&data).unwrap();
    let c = f.cmap().unwrap();
    let sub = |p, e, fm| (0..c.len()).filter_map(|i| c.subtable(i)).find(|s| (s.platform_id, s.encoding_id, s.format) == (p, e, fm));
    let f4 = sub(3, 1, 4).expect("fmt4");
    let f12 = sub(3, 10, 12).expect("fmt12");
    let f6 = sub(1, 0, 6).expect("fmt6");
    let mut n = 0;
    f4.for_each(|cp, g| {
        assert_eq!(f12.glyph(cp), Some(g), "U+{cp:04X}");
        n += 1;
    });
    assert!(n > 3000, "fmt4 mapped only {n}");
    for cp in (b'A'..=b'Z').chain(b'a'..=b'z') {
        assert_eq!(f6.glyph(cp as u32), f4.glyph(cp as u32));
    }
    // Format 12 reaches beyond the BMP where format 4 cannot.
    let mut astral = 0;
    f12.for_each(|cp, _| astral += (cp > 0xFFFF) as u32);
    assert!(astral > 0);
}

#[test]
fn gsub_ligatures_and_gpos_pairs_match_fonttools() {
    use font_core::layout::{ligature_subst, pair_adjust};
    let (mut n_lig, mut n_pair, mut fonts) = (0, 0, 0);
    for k in kat_data::LAYOUT_KATS {
        let Some(data) = common::load(k.path, None) else { continue };
        let f = Font::parse(&data).unwrap();
        fonts += 1;
        if let Some(g) = f.gsub {
            assert_eq!(g.0.lookups_for(*b"latn", &[*b"liga"]).as_slice(), k.liga_lookups, "{} liga lookups", k.path);
            for l in k.ligs {
                let mut got = None;
                let lk = g.0.lookup(l.lookup).unwrap();
                assert_eq!(lk.kind, 4);
                for st in &lk.subtables {
                    if let Some(r) = ligature_subst(st, l.first, |j| l.rest.get(j - 1).copied()) {
                        got = Some(r);
                        break;
                    }
                }
                assert_eq!(got, Some((l.lig, l.rest.len() + 1)), "{} lig {} {:?}", k.path, l.first, l.rest);
                n_lig += 1;
            }
        }
        if let Some(g) = f.gpos {
            assert_eq!(g.0.lookups_for(*b"latn", &[*b"kern"]).as_slice(), k.kern_lookups, "{} kern lookups", k.path);
            for p in k.pairs {
                let lk = g.0.lookup(p.lookup).unwrap();
                assert_eq!(lk.kind, 2);
                let got = lk.subtables.iter().find_map(|st| pair_adjust(st, p.first, p.second)).map(|(v1, _, _)| v1.x_advance);
                assert_eq!(got, Some(p.x_adv1), "{} pair {} {}", k.path, p.first, p.second);
                n_pair += 1;
            }
        }
    }
    eprintln!("LAYOUT KAT: {fonts} fonts, {n_lig} ligatures, {n_pair} GPOS pairs");
    assert!(fonts > 0);
}
