#!/usr/bin/env python3
# SPDX-License-Identifier: LGPL-3.0-or-later
# Copyright (C) 2026 The Architect & Una
#
# INFERCORE (SR57): generate src/unicode_tables.rs — DATA ONLY — from the Unicode Character Database.
#
#   tools/gen_unicode.py UnicodeData-8.0.0.txt UnicodeData-9.0.0.txt > src/unicode_tables.rs
#
# The two files are pinned in vectors.txt (URL + sha256). Why two versions: the reference BERT
# tokenizer (HF `tokenizers`, whose ids INFERCORE must reproduce byte for byte) takes its general
# categories from the `unicode_categories` 0.1.1 tables (generated from UnicodeData.txt 8.0.0) and
# its NFD from `unicode-normalization-alignments` 0.1.12 (Unicode 9.0.0). Matching the reference
# means matching ITS data, so this script reads exactly those two releases.
#
# `<..., First>` / `<..., Last>` row pairs are ranges (UCD §4.2.3); of the categories read here only
# Co (private use) has them. Cs rows are dropped (Rust chars cannot be surrogates). Nothing here uses
# Python's own unicodedata module.
import sys

def rows(path):
    first = None
    with open(path, encoding='utf-8') as f:
        for line in f:
            p = line.rstrip('\n').split(';')
            if len(p) < 6:
                continue
            cp = int(p[0], 16)
            if p[1].endswith(', First>'):
                first = cp
                continue
            if p[1].endswith(', Last>'):
                for c in range(first, cp + 1):
                    yield c, p[2], int(p[3]), p[5]
                first = None
                continue
            yield cp, p[2], int(p[3]), p[5]

def ranges(cps):
    cps = sorted(set(cps))
    out = []
    for c in cps:
        if out and out[-1][1] + 1 == c:
            out[-1][1] = c
        else:
            out.append([c, c])
    return out

def emit_ranges(name, doc, cps):
    rs = ranges(cps)
    print(f'/// {doc} ({len(rs)} ranges, {len(set(cps))} code points).')
    print(f'pub static {name}: &[(u32, u32)] = &[')
    line = '   '
    for a, b in rs:
        item = f' (0x{a:X}, 0x{b:X}),'
        if len(line) + len(item) > 100:
            print(line)
            line = '   '
        line += item
    print(line)
    print('];\n')

def main():
    u8, u9 = sys.argv[1], sys.argv[2]
    other, mn, punct = [], [], []
    for cp, gc, _, _ in rows(u8):
        if gc == 'Cs':
            continue
        if gc in ('Cc', 'Cf', 'Co'):
            other.append(cp)
        if gc == 'Mn':
            mn.append(cp)
        if gc in ('Pc', 'Pd', 'Ps', 'Pe', 'Pi', 'Pf', 'Po'):
            punct.append(cp)
    ccc, decomp = {}, {}
    for cp, gc, cc, dm in rows(u9):
        if cc:
            ccc[cp] = cc
        if dm and not dm.startswith('<'):
            decomp[cp] = [int(x, 16) for x in dm.split()]
    def full(cp):
        if cp not in decomp:
            return [cp]
        return [y for x in decomp[cp] for y in full(x)]
    print('// SPDX-License-Identifier: LGPL-3.0-or-later')
    print('// Copyright (C) 2026 The Architect & Una')
    print('//')
    print('// GENERATED by tools/gen_unicode.py from UnicodeData.txt 8.0.0 (categories) and 9.0.0')
    print('// (NFD) — see vectors.txt for the pinned sources. DATA ONLY. Never hand-edit.')
    print('#![allow(clippy::unreadable_literal)]\n')
    emit_ranges('OTHER', 'Cc | Cf | Co, UnicodeData 8.0.0 (the reference `is_other`)', other)
    emit_ranges('MARK_NONSPACING', 'Mn, UnicodeData 8.0.0', mn)
    emit_ranges('PUNCTUATION', 'Pc | Pd | Ps | Pe | Pi | Pf | Po, UnicodeData 8.0.0', punct)
    # Canonical combining class runs (9.0.0).
    runs = []
    for cp in sorted(ccc):
        if runs and runs[-1][1] + 1 == cp and runs[-1][2] == ccc[cp]:
            runs[-1][1] = cp
        else:
            runs.append([cp, cp, ccc[cp]])
    print(f'/// Canonical_Combining_Class != 0, UnicodeData 9.0.0 ({len(runs)} runs): (first, last, ccc).')
    print('pub static CCC: &[(u32, u32, u8)] = &[')
    line = '   '
    for a, b, c in runs:
        item = f' (0x{a:X}, 0x{b:X}, {c}),'
        if len(line) + len(item) > 100:
            print(line); line = '   '
        line += item
    print(line); print('];\n')
    # Full (recursive) canonical decompositions (9.0.0); Hangul syllables are algorithmic (in code).
    chars, idx = [], []
    for cp in sorted(decomp):
        d = full(cp)
        idx.append((cp, len(chars), len(d)))
        chars.extend(d)
    assert len(chars) < 65536 and max(n for _, _, n in idx) < 256
    print(f'/// Full canonical decompositions, UnicodeData 9.0.0 ({len(idx)} code points):')
    print('/// (code point, offset into DECOMP_CHARS, length).')
    print('pub static DECOMP: &[(u32, u16, u8)] = &[')
    line = '   '
    for cp, o, n in idx:
        item = f' (0x{cp:X}, {o}, {n}),'
        if len(line) + len(item) > 100:
            print(line); line = '   '
        line += item
    print(line); print('];\n')
    print(f'/// The decomposed code points ({len(chars)}).')
    print('pub static DECOMP_CHARS: &[u32] = &[')
    line = '   '
    for c in chars:
        item = f' 0x{c:X},'
        if len(line) + len(item) > 100:
            print(line); line = '   '
        line += item
    print(line); print('];')

main()
