#!/usr/bin/env python3
# SPDX-License-Identifier: LGPL-3.0-or-later
# Copyright (C) 2026 The Architect & Una
#
# VP8CORE (SR40): generate src/tables.rs — the RFC 6386 constant tables (default token probabilities
# §13.5, token update probabilities §13.4, key-frame sub-block mode probabilities §11.5, mode
# probabilities §11.2/§16.1, motion-vector probabilities §17.2, quantizer lookup §14.1, split-MV
# tables §16.4). The RFC host (rfc-editor.org / ietf.org) is not reachable through this container's
# proxy, so the numbers are read from the libvpx source files that RFC 6386 §20 ("Attachment One:
# Reference Decoder Source Code") itself ships — the same tables, byte for byte. Only DATA is taken;
# the decoder is written from the RFC prose. The KATs (bit-exact MD5s) are the proof the numbers
# are right.
#
# usage: gen_tables.py <dir holding the fetched .c/.h files>  > src/tables.rs
#   fetched from https://raw.githubusercontent.com/webmproject/libvpx/main/vp8/common/<file>
import re, sys

d = sys.argv[1]

def src(name):
    s = open(f"{d}/{name}").read()
    s = re.sub(r"/\*.*?\*/", "", s, flags=re.S)
    return re.sub(r"//[^\n]*", "", s)

def array(name, file):
    s = src(file)
    m = re.search(re.escape(name) + r"\s*(\[[^=]*\])?\s*=\s*\{", s)
    if not m:
        raise SystemExit(f"{name} not found in {file}")
    i, depth = m.end(), 1
    while depth:
        depth += {"{": 1, "}": -1}.get(s[i], 0)
        i += 1
    return [int(x) for x in re.findall(r"-?\d+", s[m.end():i])]

def emit(rname, ty, dims, vals):
    n = 1
    for x in dims:
        n *= x
    assert len(vals) == n, (rname, len(vals), n)
    def nest(v, ds):
        if len(ds) == 1:
            return "[" + ", ".join(str(x) for x in v) + "]"
        step = len(v) // ds[0]
        return "[\n" + ",\n".join(nest(v[k * step:(k + 1) * step], ds[1:]) for k in range(ds[0])) + "]"
    t = ty
    for x in reversed(dims):
        t = f"[{t}; {x}]"
    print(f"pub const {rname}: {t} = {nest(vals, dims)};\n")

print("// SPDX-License-Identifier: LGPL-3.0-or-later\n// Copyright (C) 2026 The Architect & Una\n//")
print("//! RFC 6386 constant tables. GENERATED by tools/gen_tables.py — never hand-edit.\n")
print("#![allow(clippy::all)]\n")
emit("DEFAULT_COEF_PROBS", "u8", [4, 8, 3, 11], array("default_coef_probs", "default_coef_probs.h"))
emit("COEF_UPDATE_PROBS", "u8", [4, 8, 3, 11], array("vp8_coef_update_probs", "coefupdateprobs.h"))
emit("KF_BMODE_PROBS", "u8", [10, 10, 9], array("vp8_kf_bmode_prob", "vp8_entropymodedata.h"))
emit("KF_YMODE_PROBS", "u8", [4], array("vp8_kf_ymode_prob", "vp8_entropymodedata.h"))
emit("KF_UV_MODE_PROBS", "u8", [3], array("vp8_kf_uv_mode_prob", "vp8_entropymodedata.h"))
emit("YMODE_PROBS", "u8", [4], array("vp8_ymode_prob", "vp8_entropymodedata.h"))
emit("UV_MODE_PROBS", "u8", [3], array("vp8_uv_mode_prob", "vp8_entropymodedata.h"))
emit("BMODE_PROBS", "u8", [9], array("vp8_bmode_prob", "vp8_entropymodedata.h"))
emit("MV_UPDATE_PROBS", "u8", [2, 19], array("vp8_mv_update_probs", "entropymv.c"))
emit("DEFAULT_MV_PROBS", "u8", [2, 19], array("vp8_default_mv_context", "entropymv.c"))
emit("DC_QLOOKUP", "i32", [128], array("dc_qlookup", "quant_common.c"))
emit("AC_QLOOKUP", "i32", [128], array("ac_qlookup", "quant_common.c"))
emit("SUB_MV_REF_PROBS", "u8", [5, 3], array("vp8_sub_mv_ref_prob2", "entropymode.c"))
emit("MBSPLITS", "u8", [4, 16], array("vp8_mbsplits", "entropymode.c"))
emit("MBSPLIT_PROBS", "u8", [3], array("vp8_mbsplit_probs", "entropymode.c"))
