#![no_std]
// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 The Architect & Una
//
// XUSBFW (jetson bench): the Tegra234 XUSB Falcon firmware, injected at build time.
//
// The whole crate is one `const`:
//
//     pub const XUSB_FW: Option<&[u8]>;
//
// `None` unless the operator pointed `UNAOS_XUSB_FW_PATH` at an absolute extern path when this
// crate was compiled, in which case it is `Some(include_bytes!("<that path>"))` — read in place,
// never copied into the tree or `target/`. See `build.rs` for the injection rules and
// `Cargo.toml` for why this lives outside the kernel crate.
//
// The kernel pulls this in ONLY under its `xusbfw` feature (an optional dependency), so a default
// build neither compiles this crate nor carries a build script of its own.

// Generated by build.rs into this crate's OUT_DIR. Declares `pub const XUSB_FW: Option<&[u8]>`.
include!(concat!(env!("OUT_DIR"), "/xusb_fw.rs"));
