// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 The Architect & Una
//
// XUSBFW (jetson): build-time injection point for the Tegra234 XUSB Falcon firmware blob.
//
// The blob is bench-only and MUST NEVER enter git or any built medium (users fetch NVIDIA firmware
// themselves; UnaOS ships only process docs). So this script embeds it ONLY when the caller has
// pointed `UNAOS_XUSB_FW_PATH` at an absolute extern path (the bunker blob), and emits a `None`
// stub otherwise:
//
//   * path unset -> `None` (the scaffold witnesses a no-op: "no firmware path set");
//   * path set   -> `Some(include_bytes!("<abs path>"))` read DIRECTLY from the bunker, never
//     copied into the tree or `target/` — the bytes land in `.rodata` only for this deliberate,
//     bench-only build;
//   * path set but not absolute, or set but unreadable -> the build FAILS LOUDLY here, naming the
//     path and the OS error. A typo'd bench path must never silently degrade into a `None` build
//     that then witnesses "no firmware path set" and looks like a successful skip.
//
// The generated file lands in THIS crate's OUT_DIR and is `include!`d only from `src/lib.rs`.
//
// WHY THIS SCRIPT IS NOT IN THE KERNEL CRATE. It was, at 12b0993c, and the commit claimed the
// default build stayed "byte-identical". That claim was FALSE and was measured false: a build
// script's mere presence changes cargo's `-C metadata` for the crate carrying it, which reseeds the
// v0 symbol disambiguator and re-lays out `.text`/`.rodata`. Knob-off `kernel.elf` grew 1608 B and
// knob-off `kernel8.img` differed throughout. Living in its own crate, taken by the kernel as an
// optional dependency, this script exists only in builds that actually asked for the firmware —
// the knob-off kernel carries no build script at all and its disambiguator is unchanged. See
// Cargo.toml's header for the full measurement.

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    // Re-run when the caller sets/clears the firmware path so a knob flip is picked up.
    println!("cargo:rerun-if-env-changed=UNAOS_XUSB_FW_PATH");

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR set by cargo");
    let stub = Path::new(&out_dir).join("xusb_fw.rs");

    let fw_path = env::var("UNAOS_XUSB_FW_PATH").ok().filter(|p| !p.is_empty());

    let body = match fw_path {
        Some(path) => {
            // Absolute extern path (the bunker blob). `include_bytes!` reads it in place — no copy
            // is ever made into the repo or target/. Register it as a build dependency so a blob
            // update rebuilds.
            //
            // Both checks below are LOUD by design: a build-script panic aborts cargo with exit 101
            // and prints this message verbatim, before a single crate is codegen'd. The old
            // in-kernel script leaned on `include_bytes!`'s own "couldn't read <path>" error, which
            // said the same thing later and with less context; this says it here, and also catches
            // the relative-path case, which `include_bytes!` would have resolved against OUT_DIR
            // (i.e. against a directory that has nothing to do with what the operator typed).
            if !Path::new(&path).is_absolute() {
                panic!(
                    "XUSBFW: UNAOS_XUSB_FW_PATH must be an ABSOLUTE extern path to the firmware \
                     blob (the bench copy is read in place, never staged into the tree), got: \
                     {path}"
                );
            }
            if let Err(e) = fs::File::open(&path) {
                panic!(
                    "XUSBFW: UNAOS_XUSB_FW_PATH is set but the firmware blob could not be read: \
                     {path}: {e}"
                );
            }
            println!("cargo:rerun-if-changed={path}");
            // Debug-formatted string literal so backslashes/quotes escape.
            format!(
                "// GENERATED by build.rs — bench-only firmware embed (UNAOS_XUSB_FW_PATH set).\n\
                 pub const XUSB_FW: Option<&[u8]> = Some(include_bytes!({path:?}));\n"
            )
        }
        None => {
            // Witnessed-no-op path: no firmware bytes. This is what every build that arms the
            // `xusbfw` knob WITHOUT a blob path gets; a default build does not compile this crate
            // at all.
            "// GENERATED by build.rs — blob-free (no UNAOS_XUSB_FW_PATH: no firmware embedded).\n\
             pub const XUSB_FW: Option<&[u8]> = None;\n"
                .to_string()
        }
    };

    fs::write(&stub, body).expect("write xusb_fw.rs stub");
}
