#!/usr/bin/env python3
# SPDX-License-Identifier: GPL-3.0-or-later
# Copyright (C) 2026 The Architect & Una
#
# SELFDIAG (rmbp-ledger B324, R82): the witness OWNERS table. Every `":: TAG:` string literal under
# unaos/crates/kernel/src is a site that prints a witness line; the diagnosis program (APPS/DIAG.ELF) pairs a
# boot's FAIL line with the file that prints it through this table, staged by the builder as
# /system/witness-owners.txt (ESP and DATA trees). Format (diag_core::owners): one row per site,
# `TAG<TAB>repo-relative path<TAB>1-based line`; the rows of one tag put the sites whose source line names
# FAIL first (the verdict a diagnosis looks for), then file order. `#` lines are comments.
#
# usage: witness-owners.py <unaos dir> <out file>
import os
import re
import sys

SITE = re.compile(r'":: ([A-Za-z0-9_-]{1,32}):')


def main():
    if len(sys.argv) != 3:
        sys.stderr.write("usage: witness-owners.py <unaos dir> <out file>\n")
        return 2
    unaos = os.path.abspath(sys.argv[1])
    repo = os.path.dirname(unaos)
    src = os.path.join(unaos, "crates", "kernel", "src")
    rows = {}
    order = []
    for root, dirs, files in os.walk(src):
        dirs.sort()
        for f in sorted(files):
            if not f.endswith(".rs"):
                continue
            p = os.path.join(root, f)
            rel = os.path.relpath(p, repo)
            with open(p, encoding="utf-8", errors="replace") as fh:
                for n, line in enumerate(fh, 1):
                    for m in SITE.finditer(line):
                        t = m.group(1)
                        if t not in rows:
                            rows[t] = []
                            order.append(t)
                        rows[t].append((0 if "FAIL" in line else 1, len(rows[t]), rel, n))
    total = 0
    with open(sys.argv[2], "w", encoding="utf-8") as out:
        out.write("# witness owners: TAG<TAB>path<TAB>line (generated by unaos/scripts/witness-owners.py)\n")
        for t in sorted(order):
            for _, _, rel, n in sorted(rows[t]):
                out.write("%s\t%s\t%d\n" % (t, rel, n))
                total += 1
    print("   witness-owners: %d tags, %d sites -> %s" % (len(order), total, sys.argv[2]))
    return 0 if total else 1


if __name__ == "__main__":
    sys.exit(main())
