#!/usr/bin/env python3
# SELFBUILD6 (B360): assemble src/tramp.S (clang, x86_64) and write src/tramp_bytes.rs — the code page's bytes and the
# offset of every global entry. Run from the crate root: python3 tools/gen_tramp.py [--check]
import os, subprocess, sys, tempfile
root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
src = os.path.join(root, "src", "tramp.S")
out = os.path.join(root, "src", "tramp_bytes.rs")
def build():
    with tempfile.TemporaryDirectory() as d:
        o, b = os.path.join(d, "t.o"), os.path.join(d, "t.bin")
        subprocess.check_call(["clang", "-c", "--target=x86_64-unknown-linux-gnu", src, "-o", o])
        rel = subprocess.check_output(["readelf", "-rW", o]).decode()
        if "Relocation section" in rel:
            sys.exit("tramp.S assembled WITH relocations: the page must be position-independent\n" + rel)
        subprocess.check_call(["llvm-objcopy", "-O", "binary", "--only-section=.text", o, b])
        code = open(b, "rb").read()
        nm = subprocess.check_output(["nm", o]).decode()
    syms = {}
    for line in nm.splitlines():
        p = line.split()
        if len(p) == 3 and p[1] == "T":
            syms[p[2]] = int(p[0], 16)
    rows = ["// SPDX-License-Identifier: GPL-3.0-or-later", "// GENERATED by tools/gen_tramp.py from src/tramp.S — do not edit.", ""]
    rows.append("/// The code page's bytes (assembled `tramp.S`).")
    rows.append("pub const TRAMP_CODE: [u8; %d] = [" % len(code))
    for i in range(0, len(code), 16):
        rows.append("    " + " ".join("0x%02x," % c for c in code[i:i + 16]))
    rows.append("];")
    for k in sorted(syms, key=lambda k: syms[k]):
        if k.startswith("t_"):
            rows.append("pub const %s: u64 = %d;" % (k.upper(), syms[k]))
    return "\n".join(rows) + "\n"
text = build()
if "--check" in sys.argv:
    sys.exit(0 if open(out).read() == text else 1)
open(out, "w").write(text)
print("wrote", out)
