//! M2 — Selectors Level 4 proven on WPT's matching tests, re-expressed over the test DOM.
//!
//! * dom/nodes/ParentNode-querySelector-All (HTML): selectors.js's invalid selectors (must not parse) and
//!   valid selectors in the Document, In-document Element and Detached Element contexts.
//! * css/selectors: has-basic, has-relative-argument, is-where-basic, is-where-not, not-complex
//!   (`main.querySelectorAll` / `querySelector` / `closest` / `matches`), and
//!   attribute-selectors/attribute-case/semantics (the `i` / `s` flags, standards-mode HTML).
//! Fixtures: tests/wpt/*.json, regenerated by tools/wpt-fixtures.mjs from one pinned WPT commit.
mod common;
use common::dom::{Dom, El};
use common::json::{self, Json};

use css_core::matching::{matches_list, MatchContext};
use css_core::parser::{parse_stylesheet_rules, Rule};
use css_core::selectors::*;
use css_core::{ComponentValue, Token};

fn ids(dom: &Dom, v: &[usize]) -> Vec<String> {
    v.iter().map(|&i| dom.id_of(i).unwrap_or("").to_string()).collect()
}

/// Elements of `candidates` matching `list`, with `scope` as `:scope`.
fn select(dom: &Dom, list: &SelectorList, scope: Option<usize>, candidates: &[usize]) -> Vec<usize> {
    let sc = scope.map(|s| dom.el(s));
    let cx = MatchContext { scope: sc.as_ref() };
    candidates.iter().copied().filter(|&i| matches_list(list, &dom.el(i), &cx)).collect()
}

fn strs(j: &Json) -> Vec<String> {
    j.arr().iter().map(|x| x.str().to_string()).collect()
}

#[test]
fn m2_wpt_selectors_api() {
    let fx = json::parse(include_str!("wpt/selectors-api.json"));
    let mut doc = Dom::from_json(fx.get("dom_document").unwrap());
    doc.target = Some("target".into());
    let root = doc.by_id("root").unwrap();
    // In-document Element context: a data-clone copy of #root appended to <body> first.
    let mut el_dom = doc.clone();
    let body = el_dom.by_name("body").unwrap();
    el_dom.copy_subtree(&doc, root, Some(body), Some("data-clone"));
    // Detached Element context: a clone of #root with no parent.
    let mut det = Dom { in_document: false, target: Some("target".into()), ..Default::default() };
    det.copy_subtree(&doc, root, None, None);

    let ns = Namespaces::default();
    let (mut ip, mut it) = (0, 0);
    for s in fx.get("invalid").unwrap().arr() {
        it += 1;
        if parse_selector_str(s.str(), &ns).is_err() {
            ip += 1;
        } else {
            println!("  FAIL invalid selector parsed: {:?}", s.str());
        }
    }
    println!("selectors-api invalid selectors rejected: {ip}/{it}");

    let (mut vp, mut vt) = (0, 0);
    for case in fx.get("valid").unwrap().arr() {
        let sel = case.get("selector").unwrap().str();
        let expect = strs(case.get("expect").unwrap());
        for c in case.get("ctx").unwrap().arr() {
            vt += 1;
            let got = match parse_selector_str(sel, &ns) {
                Err(_) => None,
                Ok(list) => Some(match c.str() {
                    "document" => ids(&doc, &select(&doc, &list, None, &doc.preorder(0))),
                    "element" => {
                        let r = el_dom.by_id("root").unwrap();
                        let cand: Vec<usize> = el_dom.preorder(r)[1..].to_vec();
                        ids(&el_dom, &select(&el_dom, &list, Some(r), &cand))
                    }
                    _ => {
                        let cand: Vec<usize> = det.preorder(0)[1..].to_vec();
                        ids(&det, &select(&det, &list, Some(0), &cand))
                    }
                }),
            };
            if got.as_ref() == Some(&expect) {
                vp += 1;
            } else {
                println!("  FAIL [{}] {:?} ({}): want {:?} got {:?}", c.str(), sel, case.get("name").unwrap().str(), expect, got);
            }
        }
    }
    println!("selectors-api valid selectors: {vp}/{vt}");
    assert_eq!((ip, vp), (it, vt));
}

#[test]
fn m2_wpt_css_selectors() {
    let fx = json::parse(include_str!("wpt/css-selectors.json"));
    let ns = Namespaces::default();
    let mut all = (0, 0);
    for suite in fx.get("suites").unwrap().arr() {
        let file = suite.get("file").unwrap().str();
        let dom = Dom::from_json(suite.get("dom").unwrap());
        let main = dom.by_id(suite.get("scope").unwrap().str()).or_else(|| dom.by_name("main")).unwrap();
        let below: Vec<usize> = dom.preorder(main)[1..].to_vec();
        let (mut p, mut t) = (0, 0);
        for case in suite.get("cases").unwrap().arr() {
            t += 1;
            let sel = case.get("selector").unwrap().str();
            let mut expect = strs(case.get("expect").unwrap());
            let got: Option<Vec<String>> = parse_selector_str(sel, &ns).ok().map(|list| match case.get("kind").unwrap().str() {
                "all" => {
                    let mut v = ids(&dom, &select(&dom, &list, Some(main), &below));
                    v.sort();
                    expect.sort();
                    v
                }
                "first" => ids(&dom, &select(&dom, &list, Some(main), &below)).into_iter().take(1).collect(),
                "closest" => {
                    let mut cur = dom.by_id(case.get("node").unwrap().str());
                    let mut out = vec![];
                    while let Some(i) = cur {
                        if !select(&dom, &list, None, &[i]).is_empty() {
                            out = ids(&dom, &[i]);
                            break;
                        }
                        cur = dom.nodes[i].parent;
                    }
                    out
                }
                _ => {
                    let i = dom.by_id(case.get("node").unwrap().str()).unwrap();
                    if select(&dom, &list, None, &[i]).is_empty() { vec![] } else { vec!["true".into()] }
                }
            });
            if got.as_ref() == Some(&expect) {
                p += 1;
            } else {
                println!("  FAIL {file} {sel:?}: want {expect:?} got {got:?}");
            }
        }
        println!("{file}: {p}/{t}");
        all = (all.0 + p, all.1 + t);
    }

    // attribute-case/semantics: `<style>` text `S { visibility:hidden }` must parse and match (or not).
    let (mut p, mut t) = (0, 0);
    for case in fx.get("attribute_case").unwrap().arr() {
        t += 1;
        let s = case.get("selector").unwrap().str();
        let want = matches!(case.get("expect"), Some(Json::Bool(true)));
        let mut dom = Dom { in_document: true, ..Default::default() };
        let html = dom.push(None, "html", HTML_NS, vec![]);
        let body = dom.push(Some(html), "body", HTML_NS, vec![]);
        let attrs = case.get("attrs").unwrap().arr().iter().map(|a| (a.arr()[0].str().into(), a.arr()[1].str().into(), a.arr()[2].str().into())).collect();
        let div = dom.push(Some(body), "div", HTML_NS, attrs);
        let got = sheet_selector(&format!("{s} {{ visibility:hidden }}")).map(|list| !select(&dom, &list, None, &[div]).is_empty());
        if got == Some(want) {
            p += 1;
        } else {
            println!("  FAIL attribute-case {s:?} {:?}: want {want} got {got:?}", case.get("attrs").unwrap());
        }
    }
    println!("attribute-case/semantics: {p}/{t}");
    all = (all.0 + p, all.1 + t);
    println!("css/selectors total: {}/{}", all.0, all.1);
    assert_eq!(all.0, all.1);
}

/// The selector of the (single) style rule of a stylesheet, honouring its `@namespace` rules.
fn sheet_selector(css: &str) -> Option<SelectorList> {
    let mut ns = Namespaces::default();
    let mut out = None;
    for r in parse_stylesheet_rules(css) {
        match r.ok()? {
            Rule::At(a) if a.name.eq_ignore_ascii_case("namespace") => {
                let parts: Vec<&ComponentValue> = a.prelude.iter().filter(|c| !c.is_whitespace()).collect();
                let url = |c: &ComponentValue| match c {
                    ComponentValue::Token(Token::String(s)) | ComponentValue::Token(Token::Url(s)) => Some(s.clone()),
                    _ => None,
                };
                match parts.as_slice() {
                    [u] => ns.default = Some(url(u)?),
                    [p, u] => ns.prefixes.push((p.ident()?.to_string(), url(u)?)),
                    _ => return None,
                }
            }
            Rule::Qualified(q) => out = Some(parse_selector_list(&q.prelude, &ParseContext::new(&ns)).ok()?),
            _ => return None,
        }
    }
    out
}

#[test]
fn m2_specificity_and_child_indexed() {
    let ns = Namespaces::default();
    let sp = |s: &str| {
        let l = parse_selector_str(s, &ns).unwrap();
        let x = l.0[0].specificity;
        (x.a, x.b, x.c)
    };
    // Selectors 4 §17 examples.
    assert_eq!(sp("*"), (0, 0, 0));
    assert_eq!(sp("li"), (0, 0, 1));
    assert_eq!(sp("ul li"), (0, 0, 2));
    assert_eq!(sp("ul ol+li"), (0, 0, 3));
    assert_eq!(sp("h1 + *[rel=up]"), (0, 1, 1));
    assert_eq!(sp("ul ol li.red"), (0, 1, 3));
    assert_eq!(sp("li.red.level"), (0, 2, 1));
    assert_eq!(sp("#x34y"), (1, 0, 0));
    assert_eq!(sp("#s12:not(foo)"), (1, 0, 1));
    assert_eq!(sp(".foo :is(.bar, #baz)"), (1, 1, 0));
    assert_eq!(sp(":where(#a, .b) p"), (0, 0, 1));
    assert_eq!(sp(":nth-child(2n of .a, #b)"), (1, 1, 0));
    assert_eq!(sp("p::before"), (0, 0, 2));
    assert_eq!(sp(":has(> #a, .b)"), (1, 0, 0));
    // WPT child-indexed-pseudo-class.html: the document element (and a detached element) has no siblings.
    let mut d = Dom { in_document: true, ..Default::default() };
    let html = d.push(None, "html", HTML_NS, vec![]);
    let el = El { dom: &d, i: html };
    let cx = MatchContext::new();
    for (s, want) in [
        (":first-child", true), (":last-child", true), (":only-child", true), (":first-of-type", true),
        (":last-of-type", true), (":only-of-type", true), (":nth-child(1)", true), (":nth-child(n)", true),
        (":nth-last-child(1)", true), (":nth-last-child(n)", true), (":nth-of-type(1)", true), (":nth-of-type(n)", true),
        (":nth-last-of-type(1)", true), (":nth-last-of-type(n)", true), (":nth-child(0)", false), (":nth-child(2)", false),
        (":nth-last-child(2)", false), (":nth-of-type(2)", false), (":nth-last-of-type(2)", false),
    ] {
        assert_eq!(matches_list(&parse_selector_str(s, &ns).unwrap(), &el, &cx), want, "{s}");
    }
    // nth-child-of-has.html: `div:nth-child(even of :has(span))` picks the 2nd and 4th span-holding divs.
    let mut d = Dom { in_document: true, ..Default::default() };
    let c = d.push(None, "div", HTML_NS, vec![]);
    let mut kids = vec![];
    for k in 0..10 {
        let cls = if k == 3 || k == 7 { "test" } else { "reference" };
        let x = d.push(Some(c), "div", HTML_NS, vec![(String::new(), "class".into(), cls.into())]);
        if k % 2 == 1 {
            d.push(Some(x), "span", HTML_NS, vec![]);
        }
        kids.push(x);
    }
    let l = parse_selector_str("div:nth-child(even of :has(span))", &ns).unwrap();
    let hit: Vec<usize> = kids.iter().copied().filter(|&k| matches_list(&l, &El { dom: &d, i: k }, &cx)).collect();
    assert_eq!(hit, vec![kids[3], kids[7]]);
}
