// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 The Architect & Una
//
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

//! KNURL — the diamond crosshatch milled into the title-bar control discs, integer Q16.
//!
//! # Provenance — DERIVED, not lifted
//!
//! **This material is not in the kit**, exactly as `ceramic.rs` is not. `kits/crispy/theme.json` is
//! not reachable from this repo (white-board Q4, the standing gap), it carries no `Knurl` block at
//! any revision known here, and `libs/quartzite/src/surface.rs` has no crosshatch algo. Every
//! constant below is **derived**, its provenance line says so, and no kit hash is cited above any of
//! them — a fabricated citation would be worse than the gap it papers over.
//!
//! The authority is Peter's ruling, 2026-08-09, verbatim:
//!
//! > *"same color as mac but knurled if possible to add more texture"*
//!
//! The first half of that ruling lands in `theme.rs` (the three `CTRL_*` roles become the macOS
//! hues). This module is the second half. It is **PENDING RE-LIFT** into
//! `kits/crispy/theme.json` — as a `chrome_surface.Knurl` block — the moment that kit becomes
//! reachable, on the same terms `theme.rs`'s semantic control roles are pending.
//!
//! # The physical model
//!
//! Knurling is a *milling* operation: a hardened wheel is rolled across a metal face and cuts two
//! families of parallel grooves at complementary angles, raising a lattice of pyramids between them
//! so a thumb can grip the knob. Two facts follow, and both are load-bearing here:
//!
//! 1. **It is REGULAR, not noisy.** A knurl is cut, not weathered. There is no fBm here and no
//!    lattice hash — that would model a corroded surface, not a machined one. `ceramic.rs` models
//!    the brushed *lid* and is therefore noise-based; this models the milled *knob* and is
//!    therefore periodic. The two materials are different by construction, not by parameter.
//! 2. **It is TWO families, and the bright points are their CROSSINGS.** The pyramid apex is where
//!    both grooves' crests coincide, so the field is the SUM of the two families and its maximum is
//!    the sum of their amplitudes. That is why the budget below is a sum and is asserted as one.
//!
//! # Why the diagonals need no rotation arithmetic
//!
//! A family of parallel lines at +45° is exactly the level sets of `x + y`; at -45°, of `x - y`.
//! Both are integer expressions of the pixel coordinates, so the two complementary diagonals cost
//! one add and one subtract and involve **no rotation, no float and no libm** — the angles are
//! exact rather than approximated. The field is
//!
//! ```text
//!   knurl(x, y) = 1 + AMP_A * sin(2*pi*(x + y)/PITCH) + AMP_B * sin(2*pi*(x - y)/PITCH)
//! ```
//!
//! evaluated with `paper.rs`'s shared [`sin_turn_q16`], reused rather than copied, so there is
//! exactly one sine in the kernel and paper's pinned fixture guards this user too. Nothing in this
//! file can perturb paper or ceramic: it only *calls* a shared primitive, and [`selftest`] asserts
//! both of their pinned tile hashes are unchanged as its own regression proof.
//!
//! # DISCLOSED: at this pitch the sine is sampled ONLY on its exact quarter turns
//!
//! `PITCH` is 4 and the sample coordinates are integers, so each family's phase is always an exact
//! multiple of a quarter turn and [`sin_turn_q16`] returns only the values it is *exact* at:
//! `0`, `+65536`, `0`, `-65536`. The field is therefore a **hard three-level lattice**, not a smooth
//! swell, and the whole tile holds five distinct factors:
//!
//! ```text
//!   deviation from 65536, over the 4x4 fundamental domain:
//!
//!        x=0     1      2      3
//!   y=0    0  +1311     0  -1311      +1311 = a pyramid APEX  (both families crest)
//!   y=1   +1      0    -1      0      -1311 = a groove CROSS  (both families trough)
//!   y=2    0  -1311     0  +1311        +-1 = the two families CANCEL
//!   y=3   -1      0    +1      0
//! ```
//!
//! Read it as the machined surface it models: the apexes form a diagonal sublattice generated by
//! `(2, 2)` and `(2, -2)`, i.e. **2.83 px apart** measured along either groove direction, with the
//! grooves' crossings interleaved between them at the same spacing. That 2.83 px IS the
//! perpendicular groove pitch a knurl is specified by, and it is the finest this construction can
//! reach: `PITCH = 2` would put every phase on a HALF turn, where the sine is exactly zero for both
//! families, and the material would vanish. `PITCH = 3` is not available either — `65536 % 3 != 0`,
//! so the phase step would be a rounded division rather than an exact one, and the seam would close
//! only approximately. **4 is the finest legal pitch, not a preference.**
//!
//! The hard three-level result is stated rather than hidden because it means the sine is doing no
//! interpolation here. It is also the right answer at this scale: a smooth swell at a 4-px pitch has
//! about two pixels of ramp on each flank, which reads as blur rather than as milling.
//!
//! # Legibility at `theme::CONTROL_BOX` = 24 px
//!
//! **The window chrome is drawn in device pixels and nothing magnifies it.** `wm::spawn_geometry`
//! applies its integer scale to the app's *content* only (`w * scale + 2 * BORDER`); `BORDER`,
//! `TITLE_H` and the control discs are added unscaled, and `paint_window` writes them through
//! `put_pixel` at panel coordinates. `UNAOS_FBW`/`UNAOS_FBH` change the panel geometry that content
//! scale is chosen against, not any chrome metric. So a disc is `CONTROL_BOX` **device** pixels on
//! the 2880x1800 panel, full stop — there is no hidden magnification to spend, and equally no
//! double-counting to avoid.
//!
//! That is what condemned the original 12: it was HALF the ~24 device pixels a 2x Mac gives the
//! controls this chrome is imitating, which is exactly Peter's verdict from the bench (*"window
//! buttons are very small"*). At the ruled 24:
//!
//! ```text
//!   disc diameter            24 px
//!   glyph punch-out          12 px square, centred  (ctrl_glyph's `g = d/2`)
//!   visible metal            the annulus, ~6 px thick
//!   apex lattice pitch       2.83 px
//!   apexes across a diameter ~8 per groove direction
//!   apexes on the disc face  ~28 raised + ~28 cut, over ~450 px of face
//! ```
//!
//! Roughly two full lattice cells across the annulus in every direction, at 2.83 px — a fine
//! machined texture rather than a hint of one, and the reason this material ships as designed
//! instead of as one of the fallbacks that were on the table when the disc was 12 px.
//!
//! The contrast is the 2 %-of-a-channel budget the three materials share: measured, it moves the
//! dominant channel of each `CTRL_*` hue by 6-9 levels of 255 peak to peak, pinned byte-for-byte in
//! [`selftest`] leg 4.
//!
//! One thing a future taste pass may still want, which this module does not take: extending the
//! material to the surfaces that have room for it — the title strip, the frame, the dock tiles.
//! Those are outside this arc's lane and are a one-line authorisation.
//!
//! # It MODULATES; it never replaces
//!
//! [`shade`] multiplies a colour by a Q16 factor within `1 +/- 0.02` — `paper`'s amplitude and
//! `ceramic`'s, the same contrast league, so the knurl cannot fight the palette and a role that
//! changes in `theme.rs` changes here for free (no colour is stored in this file). `shade` of black
//! is exactly black and `shade_gain` at zero gain is the identity; both are asserted.
//!
//! **DISCLOSED: the crest clips on a near-saturated hue.** `CTRL_CLOSE` is `#FF5F57`, whose red
//! channel is already 255, so the `+2 %` crest saturates and the knurl shows there as the *trough*
//! alone. It is still visible (6 levels peak to peak on red), and it is the price of Peter's ruling
//! that the hues be the real macOS ones rather than the muted derivations they replace.
//!
//! # The tile, and why seam-freedom is an IDENTITY here
//!
//! Shifting `x` by `PITCH` advances `x + y` by `PITCH` and `x - y` by `PITCH`, i.e. advances **both**
//! families' phases by exactly one whole turn; the same holds for a shift of `y` by `PITCH` (it
//! advances one argument by `+PITCH` and the other by `-PITCH`, one turn each way). So the field's
//! period is exactly `PITCH` on both axes, and [`TILE`] is `PITCH x PITCH` — the *fundamental
//! domain*. Seam-freedom is not a divisibility accident to be arranged, it is an identity:
//! `TILE_W == TILE_H == PITCH`, asserted below alongside the one divisibility fact that is real
//! (`65536 % PITCH == 0`, which is what makes each phase step an exact integer and keeps the
//! truncating division of a possibly-negative `x - y` exact rather than rounded).
//!
//! **64 bytes** of `.bss` — one cache line, resident forever. The hot path is one L1 lookup and
//! three multiplies per disc pixel; [`selftest`] leg 6 times it and puts the number on the wire.

use super::paper::{fnv1a, sin_turn_q16};

// ---------------------------------------------------------------------------
// The parameter table. EVERY line is derived — see the module header.
// ---------------------------------------------------------------------------

/// Device pixels between adjacent grooves of ONE family, measured along an axis.
///
/// DERIVED, Peter's ruling 2026-08-09 ("knurled"), and **forced rather than chosen** — see the
/// module header: `PITCH = 2` puts every phase on a half turn where both sines are exactly zero and
/// the material disappears, and `PITCH = 3` does not divide 65536 so the phase step stops being
/// exact. 4 is the finest legal value, and it yields an apex lattice at `PITCH / sqrt(2)` = 2.83 px
/// — about 8 apexes across the ruled 24-px disc, which is a knurl.
pub const PITCH: i64 = 4;

/// The `+45°` family's amplitude — 0.010 of a channel, at Q16.
///
/// DERIVED, on `ceramic.rs`'s stated rule that the materials share paper's 0.02 contrast budget:
/// the budget is split between the two families, very slightly in favour of `+45°` so the lattice
/// has a *direction* — a perfectly symmetric knurl reads as a grid, and a real one is cut by two
/// passes of a wheel that never bear identically. Produced by the kit's pinned Q16 rounding rule
/// (`0.010 * 65536 + 0.5`, truncated), the same rule `theme.rs` uses for the gloss scalars.
pub const AMP_A_Q16: i64 = 656;

/// The `-45°` family's amplitude — the remainder of the budget, at Q16.
///
/// DERIVED, same rule. One Q16 unit below [`AMP_A_Q16`]: enough that the two passes are not
/// identical, far too little to tilt the lattice visibly. [`selftest`] leg 1 pins the difference
/// with a hand-derivable identity, so the asymmetry cannot silently become symmetry.
pub const AMP_B_Q16: i64 = 655;

/// The two amplitudes are a BUDGET, not two independent knobs: a pyramid apex is where both crests
/// coincide, so their SUM is the worst-case deviation of any pixel, and it must stay inside the
/// 2 %-of-a-channel league `paper.rs` set (`AMP_Q16` = 1311) and `ceramic.rs` honours. If a future
/// taste pass moves one, it must move the other.
const _: () = assert!(AMP_A_Q16 + AMP_B_Q16 <= 1311);

/// Both families must actually be present, or this is a one-family grain and `ceramic` already has
/// one of those.
const _: () = assert!(AMP_A_Q16 > 0 && AMP_B_Q16 > 0);

// ---------------------------------------------------------------------------
// The tile
// ---------------------------------------------------------------------------

/// Tile width — the field's exact period in `x`. See the module header: this is the fundamental
/// domain, not a chosen multiple.
pub const TILE_W: usize = PITCH as usize;

/// Tile height — the field's exact period in `y`, for the same reason.
pub const TILE_H: usize = PITCH as usize;

/// Seam-freedom and phase exactness are arithmetic facts, so they are asserted rather than
/// described.
const _: () = {
    // Seam-freedom as an IDENTITY: the tile IS one period on each axis.
    assert!(TILE_W as i64 == PITCH);
    assert!(TILE_H as i64 == PITCH);
    // Each phase step is `65536 / PITCH` turns and must be an exact integer, or the wrap closes
    // only approximately AND the truncating division of a negative `x - y` stops agreeing with the
    // floor the shared sine's `& 0xFFFF` assumes.
    assert!(65536 % PITCH == 0);
    // A pitch of 1 would put both families on the pixel grid, which is not a crosshatch.
    assert!(PITCH >= 2);
};

/// The generated tile: one Q16 modulation factor per pixel of the fundamental domain, all near
/// `65536`. 64 bytes.
///
/// SAFETY: written only inside `GEN.call_once`, which `spin::Once` runs exactly once and publishes
/// with release ordering; every reader goes through [`tile`], which acquires that publication
/// before handing out the shared reference. No `&mut` ever escapes. Mirrors `ceramic::ROWS` and
/// `paper::TILE` exactly.
static mut TILE: [u32; TILE_W * TILE_H] = [0; TILE_W * TILE_H];

static GEN: spin::Once<()> = spin::Once::new();

/// The tile, generating it on the first call. Row-major, top row first.
pub fn tile() -> &'static [u32; TILE_W * TILE_H] {
    GEN.call_once(|| {
        // SAFETY: see `TILE`. `call_once` guarantees this body runs on exactly one core, with no
        // reader able to observe the buffer until it returns.
        let t = unsafe { &mut *core::ptr::addr_of_mut!(TILE) };
        generate(t);
        witness(t);
    });
    // SAFETY: see `TILE`. Shared, immutable, after the one-shot initialisation above.
    unsafe { &*core::ptr::addr_of!(TILE) }
}

/// The Q16 modulation factor at `(x, y)`, indexed modulo the tile. The one hot lookup — 64 bytes,
/// so it is an L1 hit for the whole life of the boot.
#[inline]
pub fn cell_mod(x: usize, y: usize) -> i64 {
    tile()[(y % TILE_H) * TILE_W + (x % TILE_W)] as i64
}

/// Modulate `color` (packed `0x00RRGGBB`) by the knurl at `(x, y)`, at `gain_q16` of full
/// amplitude. Three multiplies and three shifts; no division and no branch per channel beyond the
/// clamp — the same shape as [`super::ceramic::shade_gain`], and deliberately so.
///
/// `gain_q16 == 0` returns `color` unchanged, bit for bit — the property that makes "is the
/// material on?" a question with a provable answer.
#[inline]
pub fn shade_gain(color: u32, x: usize, y: usize, gain_q16: i64) -> u32 {
    let m = 65536 + (((cell_mod(x, y) - 65536) * gain_q16) >> 16);
    let mut out = 0u32;
    for shift in [16u32, 8, 0] {
        let c = ((color >> shift) & 0xFF) as i64;
        out = (out << 8) | ((c * m) >> 16).clamp(0, 255) as u32;
    }
    out
}

/// Modulate `color` by the knurl at `(x, y)`, at full amplitude — what the control discs take.
///
/// The discs are the surface the ruling names, and they are the smallest chrome object on the
/// glass; there is no headroom here for `ceramic`'s half-gain reduction, which exists so the
/// brushed grain does not compete with the disc silhouette. The knurl IS the disc's texture, so it
/// is applied as authored.
#[inline]
pub fn shade(color: u32, x: usize, y: usize) -> u32 {
    shade_gain(color, x, y, 65536)
}

// ---------------------------------------------------------------------------
// The generator — integer Q16, on paper.rs's shared sine
// ---------------------------------------------------------------------------

/// One pixel of the material: `1 + AMP_A * sin((x+y)/PITCH) + AMP_B * sin((x-y)/PITCH)`, at Q16.
///
/// Sampled on the integer coordinate rather than the pixel centre, on `ceramic.rs`'s precedent and
/// for its reason: it makes [`selftest`]'s hand-derivable identities exact rather than approximate.
/// `x - y` may be negative; `((x - y) << 16) / PITCH` is nevertheless EXACT (never rounded) because
/// `PITCH` divides 65536, which is the const-assert above, and the shared sine reduces a negative
/// phase correctly through its `& 0xFFFF`.
fn cell_q16(x: usize, y: usize) -> u32 {
    let (x, y) = (x as i64, y as i64);
    let a = sin_turn_q16(((x + y) << 16) / PITCH);
    let b = sin_turn_q16(((x - y) << 16) / PITCH);
    (65536 + ((AMP_A_Q16 * a) >> 16) + ((AMP_B_Q16 * b) >> 16)) as u32
}

/// Fill `t` with one whole tile.
fn generate(t: &mut [u32; TILE_W * TILE_H]) {
    for y in 0..TILE_H {
        for x in 0..TILE_W {
            t[y * TILE_W + x] = cell_q16(x, y);
        }
    }
}

// ---------------------------------------------------------------------------
// Witness + fixture
// ---------------------------------------------------------------------------

/// The tile's FNV-1a 64, as generated by this file's constants. Named here so a divergence is a
/// FAILED ASSERTION with a number rather than a texture nobody looks at closely enough.
pub const TILE_FNV: u64 = 0x5695_7202_a422_b4b1;

/// **The wire says which pattern is milled into the discs.** One line at first generation, naming
/// every parameter and the checksum of the tile actually produced — so a QEMU capture and a metal
/// capture can be compared to each other and to [`TILE_FNV`] without a photograph.
///
/// Deliberately NOT `witness`-gated, on `paper::witness`'s and `ceramic::witness`'s precedent: the
/// metal image is built without the `witness` feature, so a gated line is absent from the only
/// artefact that matters. Cost is one bounded serial line per boot.
fn witness(t: &[u32]) {
    serial_println!(
        "[knurl] derived=peter-2026-08-09 algo=crosshatch-2x45 pitch={} amp_a_q16={} amp_b_q16={} budget_q16={} box={} tile={}x{} hash={:#018x}",
        PITCH,
        AMP_A_Q16,
        AMP_B_Q16,
        AMP_A_Q16 + AMP_B_Q16,
        super::theme::CONTROL_BOX,
        TILE_W,
        TILE_H,
        fnv1a(t),
    );
}

/// KNURL fixture — the crosshatch is deterministic, it produces THESE factors, it costs THIS much,
/// and it has not perturbed the two shared materials it borrows from.
///
/// Seven legs, cheapest first:
///
/// 1. **Hand-checkable identities.** Four, and all exact by the construction described in the
///    module header, because at `PITCH` = 4 every phase is an exact quarter turn:
///    * `(0, 0)`: both families at phase 0, both sines exactly `0` — the factor is exactly `65536`,
///      i.e. the material's *node* is the untouched role colour.
///    * `(1, 0)`: `x + y = 1` and `x - y = 1`, both a quarter turn, both sines exactly `+65536` —
///      a pyramid apex, exactly `65536 + AMP_A + AMP_B`.
///    * `(3, 0)`: both three quarters, both sines exactly `-65536` — a groove crossing, exactly
///      `65536 - AMP_A - AMP_B`.
///    * `(0, 1)`: `x + y = 1` (`+65536`) but `x - y = -1` (`-65536`) — the two families CANCEL, and
///      what is left is exactly `AMP_A - AMP_B`. This is the leg that pins the deliberate
///      asymmetry: if the two amplitudes ever became equal it would read `65536` and fail.
///    Every one of these can be re-derived on paper from the formula in this file, so a coefficient
///    typo cannot hide behind a checksum.
/// 2. **The amplitude budget, on every pixel.** No factor may deviate from `65536` by more than
///    `AMP_A_Q16 + AMP_B_Q16`. This is the 2 %-of-a-channel promise, checked rather than asserted
///    in prose.
/// 3. **Modulation, not replacement.** `shade_gain` at zero gain is the identity on an arbitrary
///    colour, and `shade` of black is black at every tile position. A material that failed either
///    of these would be painting, not modulating.
/// 4. **The disc reference.** The three `CTRL_*` roles under this material at the four tile
///    positions of leg 1, byte for byte — so the macOS hues and the knurl are pinned together, and
///    the crest CLIP on `CTRL_CLOSE`'s saturated red (`0xFF` stays `0xFF`) is a checked fact rather
///    than a disclosure nobody verified.
/// 5. **Determinism + the pinned checksum.** Every factor is recomputed from scratch and hashed;
///    the result must equal the hash of the stored tile AND [`TILE_FNV`].
/// 6. **The two shared materials are UNPERTURBED.** `paper`'s and `ceramic`'s live tiles are
///    re-hashed here and must still equal their own pinned constants. This module reuses their
///    sine and their FNV; this leg is the proof that reusing them changed neither.
/// 7. **The cost, measured.** `shade` is the only thing this material adds to a composite and it
///    runs once per DISC PIXEL. The leg times `1 << 14` calls on the monotonic counter and puts
///    ticks-per-1024-calls on the wire, so "what did knurling the controls cost" is a number in the
///    capture rather than an estimate. The accumulator is printed, so the loop cannot be optimised
///    away.
///
/// Emits one `:: KNURL: ... ::` verdict line.
pub fn selftest() {
    let mut fails = 0usize;

    // Leg 1 — the four hand-derivable identities.
    let t = tile();
    let at = |x: usize, y: usize| t[y * TILE_W + x] as i64;
    if at(0, 0) != 65536 {
        fails += 1;
    }
    if at(1, 0) != 65536 + AMP_A_Q16 + AMP_B_Q16 {
        fails += 1;
    }
    if at(3 % TILE_W, 0) != 65536 - AMP_A_Q16 - AMP_B_Q16 {
        fails += 1;
    }
    if at(0, 1) != 65536 + AMP_A_Q16 - AMP_B_Q16 {
        fails += 1;
    }

    // Leg 2 — the amplitude budget, on every pixel.
    let budget = AMP_A_Q16 + AMP_B_Q16;
    for &m in t.iter() {
        if (m as i64 - 65536).abs() > budget {
            fails += 1;
        }
    }

    // Leg 3 — modulation, not replacement.
    if shade_gain(0x0012_3456, 1, 0, 0) != 0x0012_3456 {
        fails += 1;
    }
    for y in 0..TILE_H {
        for x in 0..TILE_W {
            if shade(0x0000_0000, x, y) != 0 {
                fails += 1;
            }
        }
    }

    // Leg 4 — the three control roles under the knurl, at node / apex / groove / cancel.
    // Read as a table: column 0 is the node and MUST be the role itself, unchanged.
    const REF: [[u32; 4]; 3] = [
        // CTRL_CLOSE 0xFF5F57 — note column 1: red stays 0xFF. That is the crest CLIPPING on an
        // already-saturated channel, disclosed in the module header and checked here.
        [0x00FF_5F57, 0x00FF_6058, 0x00F9_5D55, 0x00FF_5F57],
        // CTRL_MIN 0xFEBC2E
        [0x00FE_BC2E, 0x00FF_BF2E, 0x00F8_B82D, 0x00FE_BC2E],
        // CTRL_ZOOM 0x28C840
        [0x0028_C840, 0x0028_CC41, 0x0027_C33E, 0x0028_C840],
    ];
    const ROLES: [u32; 3] = [
        super::theme::CTRL_CLOSE,
        super::theme::CTRL_MIN,
        super::theme::CTRL_ZOOM,
    ];
    const POS: [(usize, usize); 4] = [(0, 0), (1, 0), (3, 0), (0, 1)];
    for (r, &role) in ROLES.iter().enumerate() {
        for (c, &(x, y)) in POS.iter().enumerate() {
            if shade(role, x % TILE_W, y % TILE_H) != REF[r][c] {
                fails += 1;
            }
        }
    }
    // The node column is the role itself: a knurl that moved the disc's mean is not a modulation.
    for (r, &role) in ROLES.iter().enumerate() {
        if REF[r][0] != role {
            fails += 1;
        }
    }

    // Leg 5 — determinism, then the pinned checksum.
    let mut regen = [0u32; TILE_W * TILE_H];
    generate(&mut regen);
    let stored = fnv1a(t);
    if fnv1a(&regen) != stored {
        fails += 1;
    }
    if stored != TILE_FNV {
        fails += 1;
    }

    // Leg 6 — the two shared materials are unperturbed. This module borrows paper's sine and its
    // FNV and ceramic borrows the same sine; if reusing them had changed either, these two hashes
    // would move. They are re-hashed from the LIVE tables, not read back from the constants.
    let paper_h = fnv1a(super::paper::tile());
    let ceramic_h = fnv1a(super::ceramic::rows());
    if paper_h != super::paper::TILE_FNV {
        fails += 1;
    }
    if ceramic_h != super::ceramic::ROWS_FNV {
        fails += 1;
    }

    // Leg 7 — the cost of the ONE thing this material adds per disc pixel.
    const ITERS: usize = 1 << 14;
    let t0 = crate::clock::mono_ticks();
    let mut acc = 0u32;
    for i in 0..ITERS {
        acc = acc.wrapping_add(shade(super::theme::CTRL_CLOSE, i, i >> 2));
    }
    let t1 = crate::clock::mono_ticks();
    let per_1k = match (t0, t1) {
        (Some(a), Some(b)) if b >= a => ((b - a) * 1024) / ITERS as u64,
        _ => u64::MAX,
    };

    if fails == 0 {
        serial_println!(
            ":: KNURL: crosshatch material — {}x{} pitch={} /2 families, regen hash={:#018x} == pinned, budget<={} q16, paper={:#018x} ceramic={:#018x} unchanged, shade tk/1k={} acc={:#010x} :: PASS ::",
            TILE_W, TILE_H, PITCH, stored, budget, paper_h, ceramic_h, per_1k, acc
        );
    } else {
        serial_println!(
            ":: KNURL: crosshatch material — {} leg(s) failed, hash={:#018x} want={:#018x} paper={:#018x} ceramic={:#018x} :: FAIL ::",
            fails, stored, TILE_FNV, paper_h, ceramic_h
        );
    }
}
