// SPDX-License-Identifier: GPL-3.0-or-later
// Copyright (C) 2026 The Architect & Una
//
// XUSBFW (jetson): build-time injection point for the Tegra234 XUSB Falcon firmware blob.
//
// The blob is bench-only and MUST NEVER enter git or any built medium (users fetch NVIDIA firmware
// themselves; UnaOS ships only process docs). So this script embeds it ONLY when the caller has
// BOTH armed the `xusbfw` feature AND pointed `UNAOS_XUSB_FW_PATH` at an absolute extern path
// (the bunker blob). In every other case it emits a `None` stub, so the default build — and every
// piece of boot media — is byte-identical and blob-free BY CONSTRUCTION:
//
//   * feature off  -> `None` (the `#[cfg(feature="xusbfw")]` module that `include!`s this stub is
//     not even compiled, so `include_bytes!` never runs and zero firmware bytes reach any object);
//   * feature on, path unset -> `None` (the scaffold witnesses a no-op: "no firmware path set");
//   * feature on, path set   -> `Some(include_bytes!("<abs path>"))` read DIRECTLY from the bunker,
//     never copied into the tree or `target/` — the bytes land in `.rodata` only for this
//     deliberate, bench-only build.
//
// The generated file lands in OUT_DIR and is `include!`d only from arch/aarch64/xusb_tegra.rs's
// xusbfw module. This script has NO codegen effect on a non-xusbfw build (it only emits the two
// `rerun-if-*` lines below), so adding it leaves the default build's output unchanged.

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    // Re-run when the caller sets/clears the firmware path so a knob flip is picked up.
    println!("cargo:rerun-if-env-changed=UNAOS_XUSB_FW_PATH");

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR set by cargo");
    let stub = Path::new(&out_dir).join("xusb_fw.rs");

    // CARGO_FEATURE_XUSBFW is present in the environment iff the `xusbfw` feature is enabled.
    let feature_on = env::var_os("CARGO_FEATURE_XUSBFW").is_some();
    let fw_path = env::var("UNAOS_XUSB_FW_PATH").ok().filter(|p| !p.is_empty());

    let body = match (feature_on, fw_path) {
        (true, Some(path)) => {
            // Absolute extern path (the bunker blob). `include_bytes!` reads it in place — no copy
            // is ever made into the repo or target/. Register it as a build dependency so a blob
            // update rebuilds. Use a debug-formatted string literal so backslashes/quotes escape.
            println!("cargo:rerun-if-changed={path}");
            format!(
                "// GENERATED by build.rs — bench-only firmware embed (feature=xusbfw, path set).\n\
                 pub const XUSB_FW: Option<&[u8]> = Some(include_bytes!({path:?}));\n"
            )
        }
        _ => {
            // Default / witnessed-no-op path: no firmware bytes. This is what every default build
            // and every shipped medium gets.
            "// GENERATED by build.rs — blob-free (default: no firmware embedded).\n\
             pub const XUSB_FW: Option<&[u8]> = None;\n"
                .to_string()
        }
    };

    fs::write(&stub, body).expect("write xusb_fw.rs stub");
}
