[build]
target = "../../x86_64-unaos.json"

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]
build-std-features = ["compiler-builtins-mem"]

[target.'cfg(all())']
rustflags = [
    "-C", "panic=abort",
]
