//! M3 — X.509 (RFC 5280) path validation and RFC 6125 names, against fixtures generated by Python `cryptography`
//! (tests/gen_x509_fixtures.py) — an independent DER encoder — plus the system Mozilla bundle and Wycheproof.

mod common;
use common::*;

use tls_core::error::CertError;
use tls_core::test_provider::RustCryptoProvider;
use tls_core::x509::name::{dns_name_matches, dns_within_subtree, parse_ip};
use tls_core::x509::verify::verify_server_chain;
use tls_core::x509::{Certificate, PublicKey, SignatureAlgorithm, TrustStore};

/// 2026-10-04T00:00:00Z.
const NOW: i64 = 1_791_072_000;

fn der(n: &str) -> Vec<u8> {
    std::fs::read(format!("{}/tests/data/x509/{n}.der", env!("CARGO_MANIFEST_DIR"))).unwrap()
}

fn store(roots: &[&str]) -> TrustStore {
    let mut s = TrustStore::new();
    for r in roots {
        s.add_der(&der(r)).unwrap();
    }
    s
}

fn check(roots: &[&str], chain: &[&str], host: Option<&str>) -> Result<PublicKey, CertError> {
    let p = RustCryptoProvider::new();
    let chain: Vec<Vec<u8>> = chain.iter().map(|n| der(n)).collect();
    verify_server_chain(&p, &store(roots), NOW, &chain, host)
}

#[test]
fn parses_every_fixture_field() {
    let c = Certificate::parse(&der("leaf_ok")).unwrap();
    assert_eq!(c.version, 3);
    assert_eq!(c.signature_algorithm, SignatureAlgorithm::Ecdsa(tls_core::crypto::HashAlg::Sha256));
    assert_eq!(c.not_before, 1_735_689_600); // 2025-01-01
    assert_eq!(c.not_after, 2_051_222_400); // 2035-01-01
    assert_eq!(c.san.dns, vec!["example.test".to_string(), "*.wild.example.test".to_string()]);
    assert_eq!(c.san.ip, vec![vec![127, 0, 0, 1], parse_ip("::1").unwrap()]);
    assert_eq!(c.basic_constraints, Some((false, None)));
    assert!(c.key_usage.unwrap() & 1 != 0);
    assert!(c.ext_key_usage.is_some());
    assert!(c.authority_key_id.is_some() && c.subject_key_id.is_some());
    assert_eq!(c.subject_cn.as_deref(), Some("example.test"));
    assert!(matches!(c.public_key, PublicKey::Ec { curve: tls_core::crypto::EcCurve::P256, .. }));
    let i = Certificate::parse(&der("inter")).unwrap();
    assert_eq!(i.basic_constraints, Some((true, Some(0))));
    assert_eq!(i.issuer, Certificate::parse(&der("root")).unwrap().subject);
    let nc = Certificate::parse(&der("inter_nc")).unwrap().name_constraints.unwrap();
    assert_eq!(nc.permitted_dns, vec!["allowed.test".to_string()]);
    assert_eq!(nc.excluded_dns, vec!["bad.allowed.test".to_string()]);
    assert!(matches!(Certificate::parse(&der("rsa_leaf_pss")).unwrap().signature_algorithm, SignatureAlgorithm::RsaPss { salt_len: 32, .. }));
    assert!(matches!(Certificate::parse(&der("ed_leaf")).unwrap().public_key, PublicKey::Ed25519(_)));
    assert!(Certificate::parse(&der("leaf_unknown_critical")).unwrap().unknown_critical);
    assert!(!Certificate::parse(&der("leaf_unknown_noncritical")).unwrap().unknown_critical);
}

#[test]
fn valid_chains_verify() {
    // ECDSA P-256 root → intermediate (pathLen 0) → leaf, by DNS name, by wildcard, by IPv4 and IPv6, and with no
    // name (verifier told there is none).
    for host in [Some("example.test"), Some("EXAMPLE.test."), Some("a.wild.example.test"), Some("127.0.0.1"), Some("::1"), None] {
        assert!(check(&["root"], &["leaf_ok", "inter"], host).is_ok(), "{host:?}");
    }
    // Out of order with an unrelated extra certificate.
    assert!(check(&["root"], &["leaf_ok", "unrelated", "inter"], Some("example.test")).is_ok());
    // Several anchors in the store.
    assert!(check(&["unrelated", "ed_root", "root"], &["leaf_ok", "inter"], Some("example.test")).is_ok());
    // Ed25519.
    assert!(check(&["ed_root"], &["ed_leaf"], Some("example.test")).is_ok());
    // RSA PKCS#1 v1.5 and RSASSA-PSS certificate signatures (through the provider).
    assert!(check(&["rsa_root"], &["rsa_leaf_pkcs1"], Some("example.test")).is_ok());
    assert!(check(&["rsa_root"], &["rsa_leaf_pss"], Some("example.test")).is_ok());
    // P-384 root, ecdsa-with-SHA384 over a P-256 intermediate.
    assert!(check(&["p384_root"], &["p384_leaf", "p384_inter"], Some("example.test")).is_ok());
    // Name constraints satisfied.
    assert!(check(&["root"], &["leaf_nc_ok", "inter_nc"], Some("host.allowed.test")).is_ok());
    // A non-critical unknown extension is fine.
    assert!(check(&["root"], &["leaf_unknown_noncritical", "inter"], Some("example.test")).is_ok());
}

#[test]
fn invalid_chains_are_refused_for_the_right_reason() {
    use CertError::*;
    let cases: &[(&[&str], &[&str], Option<&str>, CertError)] = &[
        (&["root"], &["leaf_ok"], Some("example.test"), UnknownIssuer), // intermediate missing
        (&["ed_root"], &["leaf_ok", "inter"], Some("example.test"), UnknownIssuer), // wrong anchor
        (&["root"], &["leaf_expired", "inter"], Some("example.test"), Expired),
        (&["root"], &["leaf_notyet", "inter"], Some("example.test"), NotYetValid),
        (&["root"], &["leaf_ok", "inter"], Some("other.test"), NameMismatch),
        (&["root"], &["leaf_ok", "inter"], Some("wild.example.test"), NameMismatch), // * needs one label
        (&["root"], &["leaf_ok", "inter"], Some("a.b.wild.example.test"), NameMismatch), // * is one label only
        (&["root"], &["leaf_ok", "inter"], Some("127.0.0.2"), NameMismatch),
        (&["root"], &["leaf_nosan", "inter"], Some("example.test"), NameMismatch), // CN is never consulted
        (&["root"], &["leaf_eku_client", "inter"], Some("example.test"), KeyUsage),
        (&["root"], &["leaf_is_ca", "inter"], Some("example.test"), KeyUsage),
        (&["root"], &["leaf_unknown_critical", "inter"], Some("example.test"), UnknownCriticalExtension),
        (&["root"], &["leaf_under_bad", "inter_not_ca"], Some("example.test"), NotCa),
        (&["root"], &["leaf_under_bad", "inter_no_certsign"], Some("example.test"), NotCa),
        (&["root"], &["leaf_under_inter2", "inter2", "inter"], Some("example.test"), PathLenExceeded),
        (&["root"], &["leaf_nc_outside", "inter_nc"], Some("evil.test"), NameConstraint),
        (&["root"], &["leaf_nc_excluded", "inter_nc"], Some("x.bad.allowed.test"), NameConstraint),
        (&[], &["leaf_ok", "inter"], Some("example.test"), NoTrustAnchors),
    ];
    for (roots, chain, host, want) in cases {
        let got = check(roots, chain, *host).err();
        assert_eq!(got.as_ref(), Some(want), "{chain:?} for {host:?}");
    }
    // A flipped bit in the leaf signature.
    let p = RustCryptoProvider::new();
    let mut leaf = der("leaf_ok");
    let n = leaf.len();
    leaf[n - 3] ^= 1;
    let r = verify_server_chain(&p, &store(&["root"]), NOW, &[leaf, der("inter")], Some("example.test"));
    assert!(matches!(r, Err(CertError::BadSignature) | Err(CertError::BadDer(_))), "{r:?}");
    // A flipped bit in the TBS (the subject public key) → signature mismatch.
    let mut leaf = der("leaf_ok");
    let at = leaf.len() / 2;
    leaf[at] ^= 1;
    assert!(verify_server_chain(&p, &store(&["root"]), NOW, &[leaf, der("inter")], None).is_err());
}

#[test]
fn rfc6125_hostname_rules() {
    assert!(dns_name_matches("example.com", "EXAMPLE.com"));
    assert!(dns_name_matches("*.example.com", "www.example.com"));
    assert!(!dns_name_matches("*.example.com", "example.com"));
    assert!(!dns_name_matches("*.example.com", "a.b.example.com"));
    assert!(!dns_name_matches("www.*.com", "www.example.com"), "wildcard only left-most");
    assert!(!dns_name_matches("w*.example.com", "www.example.com"), "no partial-label wildcards");
    assert!(!dns_name_matches("*.com", "example.com"), "wildcard needs two labels after it");
    assert!(!dns_name_matches("*", "localhost"));
    assert!(!dns_name_matches("example.com", "example.com.evil"));
    assert!(dns_name_matches("example.com.", "example.com"));
    assert!(dns_within_subtree("a.example.com", "example.com"));
    assert!(dns_within_subtree("example.com", "example.com"));
    assert!(!dns_within_subtree("badexample.com", "example.com"));
    assert!(dns_within_subtree("a.example.com", ".example.com"));
    assert!(!dns_within_subtree("example.com", ".example.com"));
    assert_eq!(parse_ip("192.168.0.1"), Some(vec![192, 168, 0, 1]));
    assert_eq!(parse_ip("01.2.3.4"), None);
    assert_eq!(parse_ip("2001:db8::1").unwrap().len(), 16);
    assert_eq!(parse_ip("::ffff:1.2.3.4").unwrap()[12..], [1, 2, 3, 4]);
    assert_eq!(parse_ip("1:2:3:4:5:6:7:8:9"), None);
}

#[test]
fn der_is_strict() {
    let good = der("root");
    // Non-minimal length (0x81 0x05 for 5), indefinite length, trailing garbage, truncation.
    assert!(Certificate::parse(&[0x30, 0x81, 0x05, 0, 0, 0, 0, 0]).is_err());
    assert!(Certificate::parse(&[0x30, 0x80, 0, 0]).is_err());
    let mut trailing = good.clone();
    trailing.push(0);
    assert!(Certificate::parse(&trailing).is_err());
    assert!(Certificate::parse(&good[..good.len() - 1]).is_err());
    // Every single-byte truncation of a real certificate fails cleanly (no panic).
    for n in 0..good.len() {
        let _ = Certificate::parse(&good[..n]);
    }
    // Every single-bit flip either fails or parses — never panics.
    for i in 0..good.len() {
        let mut b = good.clone();
        b[i] ^= 0x80;
        let _ = Certificate::parse(&b);
    }
}

#[test]
fn trust_store_from_pem_bundle() {
    // The Mozilla bundle as shipped by this host's ca-certificates (Debian builds it from Mozilla's certdata), and
    // the builder's staged copy when tools/trust-bundle has fetched it.
    let root = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("../../../../system/trust/roots.pem");
    for path in [root.to_str().unwrap(), "/etc/ssl/certs/ca-certificates.crt"] {
        let Ok(text) = std::fs::read_to_string(path) else {
            println!("trust bundle {path}: absent, skipped");
            continue;
        };
        let (store, rep) = TrustStore::from_pem(&text);
        println!("trust bundle {path}: {rep:?}");
        assert!(rep.loaded > 100, "{path}: {rep:?}");
        assert_eq!(rep.rejected, 0, "{path}: every root parses");
        assert!(store.anchors.iter().all(|a| !a.subject.is_empty()));
    }
    // A bundle with one good block and one broken block.
    let pem = format!(
        "junk\n-----BEGIN CERTIFICATE-----\n{}\n-----END CERTIFICATE-----\n-----BEGIN CERTIFICATE-----\n!!!\n-----END CERTIFICATE-----\n",
        b64(&der("root"))
    );
    let (s, rep) = TrustStore::from_pem(&pem);
    assert_eq!((rep.loaded, rep.rejected), (1, 1));
    assert_eq!(s.anchors.len(), 1);
}

fn b64(d: &[u8]) -> String {
    const T: &[u8] = b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    let mut s = String::new();
    for c in d.chunks(3) {
        let n = (c[0] as u32) << 16 | (*c.get(1).unwrap_or(&0) as u32) << 8 | *c.get(2).unwrap_or(&0) as u32;
        for i in 0..4 {
            if i <= c.len() {
                s.push(T[(n >> (18 - 6 * i) & 63) as usize] as char);
            } else {
                s.push('=');
            }
        }
    }
    s
}

/// Wycheproof ECDSA P-256/SHA-256 (DER signatures) through `CryptoProvider::ecdsa_verify` — the exact seam
/// CRYPTOCORE will implement. Fetched at test time (URL + sha256 in vectors.txt); skipped offline.
#[test]
fn wycheproof_ecdsa_p256_sha256_through_the_trait() {
    use tls_core::crypto::{CryptoProvider, EcCurve, HashAlg};
    const URL: &str = "https://raw.githubusercontent.com/C2SP/wycheproof/main/testvectors_v1/ecdsa_secp256r1_sha256_test.json";
    let script = r#"
import json,sys
d=json.load(sys.stdin)
for g in d['testGroups']:
    k=g['publicKey']['uncompressed']
    for t in g['tests']:
        print(t['tcId'],t['result'],k,t['msg'] or '-',t['sig'] or '-')
"#;
    let out = std::process::Command::new("sh")
        .arg("-c")
        .arg(format!("curl -sSf --max-time 20 {URL} | python3 -c \"{}\"", script.replace('"', "\\\"")))
        .output();
    let Ok(out) = out else {
        println!("wycheproof: no shell, skipped");
        return;
    };
    let text = String::from_utf8_lossy(&out.stdout);
    if text.lines().count() < 10 {
        println!("wycheproof: offline or fetch failed, skipped");
        return;
    }
    let p = RustCryptoProvider::new();
    let (mut pass, mut n, mut acceptable) = (0, 0, 0);
    for line in text.lines() {
        let f: Vec<&str> = line.split_whitespace().collect();
        let (id, result, key, msg, sig) = (f[0], f[1], hex(f[2]), f[3], f[4]);
        let msg = if msg == "-" { vec![] } else { hex(msg) };
        let sig = if sig == "-" { vec![] } else { hex(sig) };
        let ok = p.ecdsa_verify(EcCurve::P256, HashAlg::Sha256, &key, &msg, &sig).is_ok();
        n += 1;
        match result {
            "valid" => assert!(ok, "tcId {id} valid but rejected"),
            "invalid" => assert!(!ok, "tcId {id} invalid but accepted"),
            _ => acceptable += 1,
        }
        pass += 1;
    }
    println!("wycheproof ecdsa_secp256r1_sha256: {pass}/{n} vectors agree ({acceptable} 'acceptable')");
    assert!(n > 300);
}
