#!/usr/bin/env python3
import os
import re
import subprocess
from collections import defaultdict

def main():
    repo_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    
    # Get all tracked files to avoid binaries and .git
    try:
        files = subprocess.check_output(
            ['git', 'ls-files'], cwd=repo_root, text=True
        ).splitlines()
    except Exception as e:
        print(f"Error running git ls-files: {e}")
        return

    # regex to find UNAOS_ variables
    knob_regex = re.compile(r'(UNAOS_[A-Z0-9_]+)')
    
    # Dictionary mapping knob -> list of (filepath, line_number, line_content)
    inventory = defaultdict(list)
    
    for filepath in files:
        full_path = os.path.join(repo_root, filepath)
        # Skip some obvious non-source files if needed, but git ls-files should be okay
        if filepath == "docs/env-knobs.md" or filepath == "tools/extract-env-knobs.py":
            continue
            
        try:
            with open(full_path, 'r', errors='ignore') as f:
                for line_num, line in enumerate(f, 1):
                    matches = knob_regex.findall(line)
                    for match in set(matches):
                        inventory[match].append((filepath, line_num, line.strip()))
        except Exception:
            pass

    docs_dir = os.path.join(repo_root, "docs")
    os.makedirs(docs_dir, exist_ok=True)
    out_file = os.path.join(docs_dir, "env-knobs.md")
    
    with open(out_file, 'w') as f:
        f.write("# UNAOS Environment Knobs Inventory\n\n")
        f.write("This document is automatically generated by `tools/extract-env-knobs.py`. ")
        f.write("It lists every `UNAOS_` environment variable found in the source tree.\n\n")
        
        for knob in sorted(inventory.keys()):
            f.write(f"## `{knob}`\n\n")
            for filepath, line_num, line_content in inventory[knob]:
                # Trim long lines for the doc
                if len(line_content) > 100:
                    line_content = line_content[:97] + "..."
                f.write(f"- **{filepath}:{line_num}**\n")
                f.write(f"  ```\n  {line_content}\n  ```\n")
            f.write("\n")

    print(f"Inventory written to {out_file}")

if __name__ == '__main__':
    main()
