#!/usr/bin/env python3
"""JSCORE (SR55): generate src/unicode/*.rs from the Unicode Character Database, version 17.0.0.

Usage: python3 tools/gen_unicode.py <ucd-dir>
The UCD files are fetched (by URL, sha256-pinned in tools/ucd.txt) from the unicode-org/unicodetools repository,
which carries the released UCD under unicodetools/data/ucd/17.0.0 (unicode.org itself is not reachable from the
build cloud). Nothing here is hand-edited: every table in src/unicode/ is this script's output.
"""
import sys, os, re, hashlib

UCD = sys.argv[1]
OUT = os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', 'src', 'unicode')
MAXCP = 0x10FFFF

def lines(name):
    with open(os.path.join(UCD, name), encoding='utf-8') as f:
        for ln in f:
            ln = ln.split('#', 1)[0].strip()
            if ln:
                yield [x.strip() for x in ln.split(';')]

def cprange(s):
    if '..' in s:
        a, b = s.split('..')
        return int(a, 16), int(b, 16)
    v = int(s, 16)
    return v, v

def to_ranges(cps):
    cps = sorted(set(cps))
    out = []
    for c in cps:
        if out and out[-1][1] + 1 == c:
            out[-1][1] = c
        else:
            out.append([c, c])
    return out

def norm_ranges(rs):
    rs = sorted(rs)
    out = []
    for a, b in rs:
        if out and out[-1][1] + 1 >= a:
            out[-1][1] = max(out[-1][1], b)
        else:
            out.append([a, b])
    return out

def flat(nums, per=16):
    s = []
    for i in range(0, len(nums), per):
        s.append('    ' + ','.join(str(n) for n in nums[i:i + per]) + ',')
    return '\n'.join(s)

HEADER = "// GENERATED by tools/gen_unicode.py from the Unicode Character Database 17.0.0 — do not edit.\n"

# ---------------------------------------------------------------- binary properties
props = {}
def add_prop_file(name, wanted=None):
    for f in lines(name):
        if len(f) < 2: continue
        p = f[1]
        if wanted is not None and p not in wanted: continue
        a, b = cprange(f[0])
        props.setdefault(p, []).append((a, b))

add_prop_file('DerivedCoreProperties.txt')
add_prop_file('PropList.txt')
add_prop_file('emoji-data.txt')
add_prop_file('DerivedBinaryProperties.txt', {'Bidi_Mirrored'})
add_prop_file('DerivedNormalizationProps.txt', {'Changes_When_NFKC_Casefolded', 'Full_Composition_Exclusion'})

# General category from DerivedGeneralCategory (lists Cn explicitly)
gc_of = {}
gc_ranges = []
for f in lines('DerivedGeneralCategory.txt'):
    a, b = cprange(f[0])
    gc_ranges.append((a, b, f[1]))
gc_ranges.sort()
# unassigned
assigned = [(a, b) for a, b, c in gc_ranges if c != 'Cn']
props['Any'] = [(0, MAXCP)]
props['ASCII'] = [(0, 0x7F)]
props['Assigned'] = assigned

ES_BINARY = ['ASCII', 'ASCII_Hex_Digit', 'Alphabetic', 'Any', 'Assigned', 'Bidi_Control', 'Bidi_Mirrored',
    'Case_Ignorable', 'Cased', 'Changes_When_Casefolded', 'Changes_When_Casemapped', 'Changes_When_Lowercased',
    'Changes_When_NFKC_Casefolded', 'Changes_When_Titlecased', 'Changes_When_Uppercased', 'Dash',
    'Default_Ignorable_Code_Point', 'Deprecated', 'Diacritic', 'Emoji', 'Emoji_Component', 'Emoji_Modifier',
    'Emoji_Modifier_Base', 'Emoji_Presentation', 'Extended_Pictographic', 'Extender', 'Grapheme_Base',
    'Grapheme_Extend', 'Hex_Digit', 'IDS_Binary_Operator', 'IDS_Trinary_Operator', 'ID_Continue', 'ID_Start',
    'Ideographic', 'Join_Control', 'Logical_Order_Exception', 'Lowercase', 'Math', 'Noncharacter_Code_Point',
    'Pattern_Syntax', 'Pattern_White_Space', 'Quotation_Mark', 'Radical', 'Regional_Indicator',
    'Sentence_Terminal', 'Soft_Dotted', 'Terminal_Punctuation', 'Unified_Ideograph', 'Uppercase',
    'Variation_Selector', 'White_Space', 'XID_Continue', 'XID_Start']

prop_alias = {}
for f in lines('PropertyAliases.txt'):
    long = f[1]
    for a in [f[0]] + f[2:]:
        prop_alias.setdefault(long, []).append(a)

out = [HEADER, "//! Binary Unicode properties (ECMA-262 table-binary-unicode-properties) as sorted flat [start, end] pairs.\n"]
names = []
for i, p in enumerate(ES_BINARY):
    rs = norm_ranges(props[p])
    nums = [x for r in rs for x in r]
    out.append(f"pub static P_{p.upper()}: [u32; {len(nums)}] = [\n{flat(nums)}\n];\n")
    for a in sorted(set([p] + prop_alias.get(p, []))):
        names.append((a, p))
# Full_Composition_Exclusion is used by normalization only
names.sort()
out.append("/// (name or alias, table) — sorted by name for binary search.\npub static BINARY_PROPERTIES: [(&str, &[u32]); %d] = [\n" % len(names))
for a, p in names:
    out.append(f'    ("{a}", &P_{p.upper()}),\n')
out.append("];\n")
with open(os.path.join(OUT, 'props.rs'), 'w') as f:
    f.write(''.join(out))

# ---------------------------------------------------------------- general category
GC_ORDER = sorted(set(c for _, _, c in gc_ranges))
merged = []
for a, b, c in gc_ranges:
    if merged and merged[-1][2] == c and merged[-1][1] + 1 == a:
        merged[-1][1] = b
    else:
        merged.append([a, b, c])
gc_alias = {}  # alias -> list of short categories
groups = {'C': ['Cc', 'Cf', 'Cn', 'Co', 'Cs'], 'L': ['Ll', 'Lm', 'Lo', 'Lt', 'Lu'], 'LC': ['Ll', 'Lt', 'Lu'],
          'M': ['Mc', 'Me', 'Mn'], 'N': ['Nd', 'Nl', 'No'], 'P': ['Pc', 'Pd', 'Pe', 'Pf', 'Pi', 'Po', 'Ps'],
          'S': ['Sc', 'Sk', 'Sm', 'So'], 'Z': ['Zl', 'Zp', 'Zs']}
for f in lines('PropertyValueAliases.txt'):
    if f[0] != 'gc': continue
    short = f[1]
    members = groups.get(short, [short])
    for a in f[1:]:
        gc_alias[a] = members
out = [HEADER, "//! General_Category: ranges as flat [start, end, category] triples covering U+0000..U+10FFFF.\n"]
out.append("pub static GC_NAMES: [&str; %d] = [%s];\n" % (len(GC_ORDER), ', '.join('"%s"' % c for c in GC_ORDER)))
nums = [x for a, b, c in merged for x in (a, b, GC_ORDER.index(c))]
out.append(f"pub static GC_RANGES: [u32; {len(nums)}] = [\n{flat(nums, 18)}\n];\n")
al = sorted(gc_alias.items())
out.append("/// (value name or alias, bit mask over GC_NAMES indices).\npub static GC_ALIASES: [(&str, u32); %d] = [\n" % len(al))
for a, mem in al:
    mask = 0
    for m in mem: mask |= 1 << GC_ORDER.index(m)
    out.append(f'    ("{a}", {mask}),\n')
out.append("];\n")
with open(os.path.join(OUT, 'gc.rs'), 'w') as f:
    f.write(''.join(out))

# ---------------------------------------------------------------- scripts
sc_alias = {}
sc_long = {}
for f in lines('PropertyValueAliases.txt'):
    if f[0] != 'sc': continue
    sc_long[f[1]] = f[2]
    for a in f[1:]:
        sc_alias[a] = f[1]
SC = sorted(sc_long.keys())
sc_ranges = []
for f in lines('Scripts.txt'):
    a, b = cprange(f[0])
    long = f[1]
    short = [k for k, v in sc_long.items() if v == long][0]
    sc_ranges.append([a, b, short])
sc_ranges.sort()
merged = []
for a, b, c in sc_ranges:
    if merged and merged[-1][2] == c and merged[-1][1] + 1 == a:
        merged[-1][1] = b
    else:
        merged.append([a, b, c])
scx_ranges = []
for f in lines('ScriptExtensions.txt'):
    a, b = cprange(f[0])
    scx_ranges.append([a, b, tuple(sorted(f[1].split()))])
scx_ranges.sort()
sets = sorted(set(s for _, _, s in scx_ranges))
out = [HEADER, "//! Script and Script_Extensions. Code points not listed in SC_RANGES are Zzzz (Unknown); code points\n//! not listed in SCX_RANGES have Script_Extensions = {Script}.\n"]
out.append("pub static SC_NAMES: [&str; %d] = [%s];\n" % (len(SC), ', '.join('"%s"' % c for c in SC)))
nums = [x for a, b, c in merged for x in (a, b, SC.index(c))]
out.append(f"pub static SC_RANGES: [u32; {len(nums)}] = [\n{flat(nums, 18)}\n];\n")
setnums = []
setidx = []
for s in sets:
    setidx.append(len(setnums))
    setnums.append(len(s))
    setnums.extend(SC.index(x) for x in s)
out.append(f"/// Script sets: [len, script...] runs.\npub static SCX_SETS: [u16; {len(setnums)}] = [\n{flat(setnums, 24)}\n];\n")
merged = []
for a, b, s in scx_ranges:
    i = setidx[sets.index(s)]
    if merged and merged[-1][2] == i and merged[-1][1] + 1 == a:
        merged[-1][1] = b
    else:
        merged.append([a, b, i])
nums = [x for r in merged for x in r]
out.append(f"pub static SCX_RANGES: [u32; {len(nums)}] = [\n{flat(nums, 18)}\n];\n")
al = sorted(sc_alias.items())
out.append("pub static SC_ALIASES: [(&str, u16); %d] = [\n" % len(al))
for a, s in al:
    out.append(f'    ("{a}", {SC.index(s)}),\n')
out.append("];\n")
with open(os.path.join(OUT, 'script.rs'), 'w') as f:
    f.write(''.join(out))

# ---------------------------------------------------------------- case mapping
upper, lower, title = {}, {}, {}
ud = {}
ccc = {}
decomp = {}
rows = list(lines('UnicodeData.txt'))
i = 0
while i < len(rows):
    f = rows[i]
    cp = int(f[0], 16)
    if f[1].endswith('First>'):
        end = int(rows[i + 1][0], 16)
        i += 2
        continue
    if f[12]: upper[cp] = int(f[12], 16)
    if f[13]: lower[cp] = int(f[13], 16)
    if f[3] != '0': ccc[cp] = int(f[3])
    if f[5]:
        d = f[5].split()
        compat = d[0].startswith('<')
        if compat: d = d[1:]
        decomp[cp] = (compat, [int(x, 16) for x in d])
    i += 1
special_upper, special_lower = {}, {}
for f in lines('SpecialCasing.txt'):
    cond = f[4] if len(f) > 4 and f[4] else ''
    if cond: continue  # Final_Sigma and language-sensitive mappings are handled in code
    cp = int(f[0], 16)
    lo = [int(x, 16) for x in f[1].split()]
    up = [int(x, 16) for x in f[3].split()]
    if lo != [cp] and lo != [lower.get(cp, cp)] or len(lo) != 1: special_lower[cp] = lo
    if len(up) != 1 or up != [upper.get(cp, cp)]: special_upper[cp] = up
fold_simple = {}
fold_full = {}
for f in lines('CaseFolding.txt'):
    cp = int(f[0], 16)
    st = f[1]
    m = [int(x, 16) for x in f[2].split()]
    if st in ('C', 'S'): fold_simple[cp] = m[0]
    if st in ('C', 'F'): fold_full[cp] = m
def pairs(d):
    ks = sorted(d)
    return [x for k in ks for x in (k, d[k])]
def multi(d):
    ks = sorted(d)
    idx, data = [], []
    for k in ks:
        idx += [k, len(data), len(d[k])]
        data += d[k]
    return idx, data
out = [HEADER, "//! Case mapping: simple mappings from UnicodeData (sorted [cp, mapped] pairs), the unconditional\n//! SpecialCasing entries ([cp, offset, len] into *_DATA), and CaseFolding (C+S simple).\n"]
for name, d in (('UPPER', upper), ('LOWER', lower), ('FOLD', fold_simple)):
    p = pairs(d)
    out.append(f"pub static SIMPLE_{name}: [u32; {len(p)}] = [\n{flat(p, 16)}\n];\n")
for name, d in (('UPPER', special_upper), ('LOWER', special_lower)):
    idx, data = multi(d)
    out.append(f"pub static SPECIAL_{name}: [u32; {len(idx)}] = [\n{flat(idx, 18)}\n];\n")
    out.append(f"pub static SPECIAL_{name}_DATA: [u32; {len(data)}] = [\n{flat(data, 16)}\n];\n")
with open(os.path.join(OUT, 'case.rs'), 'w') as f:
    f.write(''.join(out))

# ---------------------------------------------------------------- normalization
excl = set()
for a, b in props['Full_Composition_Exclusion']:
    excl.update(range(a, b + 1))
comp = {}
for cp, (compat, d) in decomp.items():
    if not compat and len(d) == 2 and cp not in excl:
        comp[(d[0], d[1])] = cp
cccr = []
for cp in sorted(ccc):
    if cccr and cccr[-1][1] + 1 == cp and cccr[-1][2] == ccc[cp]:
        cccr[-1][1] = cp
    else:
        cccr.append([cp, cp, ccc[cp]])
out = [HEADER, "//! Normalization data (UAX #15): canonical combining classes, decomposition mappings and the canonical\n//! composition pairs (Full_Composition_Exclusion removed). Hangul is algorithmic, in code.\n"]
nums = [x for r in cccr for x in r]
out.append(f"pub static CCC: [u32; {len(nums)}] = [\n{flat(nums, 18)}\n];\n")
idx, data = [], []
for cp in sorted(decomp):
    compat, d = decomp[cp]
    idx += [cp, (len(data) << 6) | (len(d) << 1) | (1 if compat else 0)]
    data += d
out.append(f"/// [cp, offset<<6 | len<<1 | compat] pairs.\npub static DECOMP: [u32; {len(idx)}] = [\n{flat(idx, 16)}\n];\n")
out.append(f"pub static DECOMP_DATA: [u32; {len(data)}] = [\n{flat(data, 16)}\n];\n")
cp_ = sorted(comp.items())
nums = [x for (a, b), c in cp_ for x in (a, b, c)]
out.append(f"/// [first, second, composite] sorted by (first, second).\npub static COMPOSE: [u32; {len(nums)}] = [\n{flat(nums, 18)}\n];\n")
with open(os.path.join(OUT, 'norm.rs'), 'w') as f:
    f.write(''.join(out))

# ---------------------------------------------------------------- emoji sequences (v-flag properties of strings)
seqs = {}
def seqfile(name):
    for f in lines(name):
        prop = f[1]
        cps = f[0]
        if '..' in cps:
            a, b = cprange(cps)
            for c in range(a, b + 1):
                seqs.setdefault(prop, []).append([c])
        else:
            seqs.setdefault(prop, []).append([int(x, 16) for x in cps.split()])
seqfile('emoji-sequences.txt')
seqfile('emoji-zwj-sequences.txt')
order = ['Basic_Emoji', 'Emoji_Keycap_Sequence', 'RGI_Emoji_Flag_Sequence', 'RGI_Emoji_Modifier_Sequence',
         'RGI_Emoji_Tag_Sequence', 'RGI_Emoji_ZWJ_Sequence']
out = [HEADER, "//! Properties of strings (ECMA-262 table-binary-unicode-properties-of-strings): each table is a run of\n//! [len, cp...] sequences. RGI_Emoji is the union of the six.\n"]
for p in order:
    nums = []
    for s in seqs[p]:
        nums.append(len(s)); nums += s
    out.append(f"pub static S_{p.upper()}: [u32; {len(nums)}] = [\n{flat(nums, 16)}\n];\n")
out.append("pub static STRING_PROPERTIES: [(&str, &[u32]); %d] = [\n" % len(order))
for p in order:
    out.append(f'    ("{p}", &S_{p.upper()}),\n')
out.append("];\n")
with open(os.path.join(OUT, 'emoji.rs'), 'w') as f:
    f.write(''.join(out))
print('ok')
