# Freeze a slice of a Chromium oracle run into tests/data/chrome_kats.rs so the gate test can check it
# without Chromium: three coverage crops and every job's canvas.measureText width.
# Usage: python3 oracle/capture_kats.py <oracle outdir> > tests/data/chrome_kats.rs
import json, sys, glob, os
d = sys.argv[1]
q = lambda s: json.dumps(s, ensure_ascii=False)
def rd(p):
    b = open(p, 'rb').read(); parts = b.split(b'\n', 3); w, h = map(int, parts[1].split()); return w, h, parts[3][:w*h]
def meta(name): return dict(l.split('=', 1) for l in open(os.path.join(d, name + '.meta')).read().splitlines())
print("// GENERATED by oracle/capture_kats.py from a Chromium oracle run (headless Chromium 1194,")
print("// --font-render-hinting=none, grayscale AA). Coverage = 255 - gray. Do not edit.")
print("#![allow(dead_code)]")
print("pub struct Crop { pub id: &'static str, pub font: &'static str, pub size: f32, pub text: &'static str, pub left: f32, pub baseline: f32, pub x0: usize, pub y0: usize, pub w: usize, pub h: usize, pub cov: &'static [u8] }")
print("pub static CROPS: &[Crop] = &[")
for name, (x0, x1, y0, y1) in [('sans_fox_16', (0, 60, 4, 24)), ('loma_kern_24', (0, 70, 6, 36)), ('serif_greek_16', (0, 60, 4, 24)), ('mono_cyr_12', (0, 60, 2, 20))]:
    w, h, a = rd(os.path.join(d, name + '.chrome.pgm')); m = meta(name)
    x1 = min(x1, w); y1 = min(y1, h)
    cov = [255 - a[y * w + x] for y in range(y0, y1) for x in range(x0, x1)]
    print("Crop { id: %s, font: %s, size: %s.0, text: %s, left: %s.0, baseline: %s.0, x0: %d, y0: %d, w: %d, h: %d, cov: &[%s] }," % (
        q(name), q(m['font']), m['size'], q(m['text']), m['left'], m['baseline'], x0, y0, x1 - x0, y1 - y0, ",".join(map(str, cov))))
print("];")
print("/// (font, size, text, canvas.measureText width)")
print("pub static WIDTHS: &[(&str, f32, &str, f32)] = &[")
for p in sorted(glob.glob(os.path.join(d, '*.meta'))):
    m = dict(l.split('=', 1) for l in open(p).read().splitlines())
    print("    (%s, %s.0, %s, %s)," % (q(m['font']), m['size'], q(m['text']), m['measure'] if '.' in m['measure'] else m['measure'] + '.0'))
print("];")
