// FONTCORE line-layout oracle: Chromium lays a paragraph into a fixed-width box (ICU line breaking, CSS
// white-space: normal, same local @font-face, kerning + ligatures on); the char offsets where each line
// starts are read back with Range.getClientRects. Prints one TSV line per job:
//   font  size  width  starts(comma list of char offsets)  text
// Usage: NODE_PATH=/opt/node22/lib/node_modules node chromium_lines.js > tests/data/chrome_lines.tsv
const fs = require('fs'), os = require('os'), path = require('path');
const { chromium } = require('playwright');
const FONTS = ['/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf', '/usr/share/fonts/truetype/dejavu/DejaVuSerif.ttf',
  '/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf'];
const TEXTS = [
  'The quick brown fox jumps over the lazy dog. Pack my box with five dozen liquor jugs! How vexingly quick daft zebras jump; well-known state-of-the-art (parenthesised) phrases, 1,234.56 numbers, $40 and 15% too.',
  'Съешь же ещё этих мягких французских булок, да выпей чаю. Широкая электрификация южных губерний даст мощный толчок подъёму сельского хозяйства.',
  'Ξεσκεπάζω την ψυχοφθόρα βδελυγμία. Γαζέες καὶ μυρτιὲς δὲν θὰ βρῶ πιὰ στὸ χρυσαφὶ ξέφωτο — «εισαγωγικά» και (παρενθέσεις).',
];
const SIZES = [12, 16, 24];
const WIDTHS = [120, 200, 333];
(async () => {
  const b = await chromium.launch({ args: ['--font-render-hinting=none'] });
  const p = await b.newPage({ viewport: { width: 1200, height: 800 } });
  const dir = fs.mkdtempSync(path.join(os.tmpdir(), 'fclines'));
  console.log('# GENERATED by oracle/chromium_lines.js (headless Chromium 1194): font, size, width, line starts, text');
  for (const font of FONTS) for (const size of SIZES) for (const width of WIDTHS) for (const text of TEXTS) {
    const f = path.join(dir, 'p.html');
    fs.writeFileSync(f, `<!doctype html><meta charset=utf-8><style>@font-face{font-family:T;src:url("file://${font}")}
      body{margin:0} #t{position:absolute;left:0;top:0;width:${width}px;font:${size}px T;font-kerning:normal;
      text-rendering:geometricPrecision;white-space:normal;word-break:normal;overflow-wrap:normal;line-height:2}</style><div id=t></div>`);
    await p.goto('file://' + f);
    const starts = await p.evaluate(async (text) => {
      const t = document.getElementById('t'); t.textContent = text; await document.fonts.ready;
      const node = t.firstChild, r = document.createRange(), out = [0];
      let lastTop = null, ci = 0;
      for (let i = 0; i < text.length; ci++) {
        const cp = text.codePointAt(i), n = cp > 0xffff ? 2 : 1;
        r.setStart(node, i); r.setEnd(node, i + n);
        const rects = r.getClientRects();
        if (rects.length && text[i] !== ' ') {
          const top = rects[rects.length - 1].top;
          if (lastTop !== null && top > lastTop + 1) out.push(ci);
          lastTop = top;
        }
        i += n;
      }
      return out;
    }, text);
    console.log([font, size, width, starts.join(','), text].join('\t'));
  }
  await b.close();
})();
