# Keep the LineBreakTest-17.0.0.txt lines whose code points all lie in FONTCORE's supported ranges
# (src/linebreak/table.rs RANGES), dropping comments. Usage: python3 filter_lbtest.py LineBreakTest.txt > tests/data/lbtest_subset.txt
import sys, re
src = open('src/linebreak/table.rs').read()
ranges = [(int(a, 16), int(b, 16)) for a, b in re.findall(r'\(0x([0-9A-F]+), 0x([0-9A-F]+)\),\n', src.split('pub static TABLE')[0])]
ok = lambda c: any(a <= c <= b for a, b in ranges)
n = k = 0
print("# Subset of LineBreakTest-17.0.0.txt (sha256 e69884e0dde6a8724873f885d68c52dc14518abf9ae4ca9e2283b8773db3b752):")
print("# the test lines whose code points all fall in FONTCORE's supported ranges. Generated by oracle/filter_lbtest.py.")
for line in open(sys.argv[1], encoding='utf-8'):
    body = line.split('#')[0].strip()
    if not body: continue
    n += 1
    cps = [int(t, 16) for t in body.split() if t not in ('÷', '×')]
    if all(ok(c) for c in cps):
        print(body); k += 1
print(f"# kept {k} of {n}", file=sys.stderr)
