# FONTCORE KAT generator: reads the container's fonts with fontTools (4.66.1, the independent oracle) and
# writes tests/data/kat_data.rs. Usage: python3 oracle/gen_kat.py > tests/data/kat_data.rs
import hashlib
from fontTools.ttLib import TTFont
from fontTools.pens.areaPen import AreaPen
from fontTools.pens.boundsPen import ControlBoundsPen
import fontTools
import json
q = json.dumps

FONTS = [
    "/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf",
    "/usr/share/fonts/truetype/dejavu/DejaVuSans-Bold.ttf",
    "/usr/share/fonts/truetype/dejavu/DejaVuSerif.ttf",
    "/usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf",
    "/usr/share/fonts/truetype/liberation/LiberationSans-Regular.ttf",
    "/usr/share/fonts/opentype/tlwg/Loma.otf",
]
CPS = list(range(0x20, 0x7F)) + list(range(0xA0, 0x100)) + [0x391, 0x3B1, 0x3C9, 0x410, 0x430, 0x44F, 0x20AC, 0x2014, 0x1E9E]
assert len(CPS) == 200
OUTLINE_CHARS = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789&@ÆßéÅΩжЖ"

def order_names(f): return f.getGlyphOrder()

def r(x): return repr(float(x)) if not float(x).is_integer() else "%d.0" % x

print("// GENERATED by oracle/gen_kat.py with fontTools %s from the container's fonts — do not edit." % fontTools.version)
print("// Each font is identified by sha256; a test skips a font whose file is absent or differs.")
print("#![allow(dead_code)]")
print("pub struct Outline { pub ch: char, pub glyph: u16, pub contours: usize, pub area: f64, pub cbox: [f64; 4] }")
print("pub struct Comp { pub glyph: u16, pub dx: i32, pub dy: i32 }")
print("pub struct Composite { pub glyph: u16, pub name: &'static str, pub comps: &'static [Comp] }")
print("pub struct Kat { pub path: &'static str, pub sha256: &'static str, pub num_glyphs: u16, pub upem: u16,")
print("  pub hhea: [i16; 3], pub typo: [i16; 3], pub win: [u16; 2], pub x_height: i16, pub cap_height: i16, pub weight: u16,")
print("  pub italic_angle: f32, pub underline: [i16; 2], pub fixed_pitch: bool, pub is_cff: bool,")
print("  pub advances_az: [u16; 26], pub cmap: &'static [(u32, u16)], pub outlines: &'static [Outline],")
print("  pub cff_widths: &'static [f32], pub composites: &'static [Composite], pub names: &'static [(u16, &'static str)], pub kern_pairs: &'static [(u16, u16, i16)], pub kern_count: usize }")
print("pub static KATS: &[Kat] = &[")
for p in FONTS:
    sha = hashlib.sha256(open(p, "rb").read()).hexdigest()
    f = TTFont(p)
    gs = f.getGlyphSet()
    cmap = f.getBestCmap()
    gid = f.getGlyphID
    hh = f["hhea"]; os2 = f["OS/2"]; post = f["post"]; head = f["head"]
    print("Kat { path: %s, sha256: %s, num_glyphs: %d, upem: %d," % (q(p), q(sha), f["maxp"].numGlyphs, head.unitsPerEm))
    print("  hhea: [%d, %d, %d], typo: [%d, %d, %d], win: [%d, %d], x_height: %d, cap_height: %d, weight: %d," % (
        hh.ascent, hh.descent, hh.lineGap, os2.sTypoAscender, os2.sTypoDescender, os2.sTypoLineGap,
        os2.usWinAscent, os2.usWinDescent, getattr(os2, "sxHeight", 0), getattr(os2, "sCapHeight", 0), os2.usWeightClass))
    print("  italic_angle: %s, underline: [%d, %d], fixed_pitch: %s, is_cff: %s," % (
        r(post.italicAngle), post.underlinePosition, post.underlineThickness, "true" if post.isFixedPitch else "false",
        "true" if "CFF " in f else "false"))
    adv = [f["hmtx"][cmap[c]][0] for c in range(ord("a"), ord("z") + 1)]
    print("  advances_az: [%s]," % ", ".join(map(str, adv)))
    print("  cmap: &[%s]," % ", ".join("(0x%X, %d)" % (c, gid(cmap[c]) if c in cmap else 0) for c in CPS))
    outs = []
    for ch in OUTLINE_CHARS:
        if ord(ch) not in cmap: continue
        name = cmap[ord(ch)]
        ap = AreaPen(gs); gs[name].draw(ap)
        bp = ControlBoundsPen(gs); gs[name].draw(bp)
        # contour count: count moveTo via a recording pen
        from fontTools.pens.recordingPen import DecomposingRecordingPen
        rp = DecomposingRecordingPen(gs); gs[name].draw(rp)
        nc = sum(1 for op, _ in rp.value if op == "moveTo" or (op == "qCurveTo" and _ and _[-1] is None))
        b = bp.bounds or (0, 0, 0, 0)
        outs.append("Outline { ch: %r, glyph: %d, contours: %d, area: %r, cbox: [%s] }" % (
            ch, gid(name), nc, float(ap.value), ", ".join(r(x) for x in b)))
    print("  outlines: &[%s]," % ",\n    ".join(outs))
    comps = []
    if "glyf" in f:
        glyf = f["glyf"]
        n = 0
        for name in ["Aacute", "Eacute", "ccedilla", "Aring", "uni1E9E", "ohungarumlaut", "Scaron", "idieresis"] + list(f.getGlyphOrder()):
            if name not in glyf or not glyf[name].isComposite(): continue
            g = glyf[name]
            if any(hasattr(c, "firstPt") for c in g.components):  # point-matched components are skipped
                continue
            cs = ", ".join("Comp { glyph: %d, dx: %d, dy: %d }" % (gid(c.glyphName), c.x, c.y) for c in g.components)
            comps.append("Composite { glyph: %d, name: %s, comps: &[%s] }" % (gid(name), q(name), cs))
            n += 1
            if n >= 12: break
    print("  composites: &[%s]," % ",\n    ".join(comps))
    cw = []
    if "CFF " in f:
        from fontTools.pens.basePen import NullPen
        cs = f["CFF "].cff.topDictIndex[0].CharStrings
        for name in order_names(f):
            c = cs[name]; c.draw(NullPen()); cw.append(r(c.width))
    print("  cff_widths: &[%s]," % ", ".join(cw))
    order = f.getGlyphOrder()
    picks = sorted(set([0, 1, 2, 3, 36, 68, 100, min(500, len(order) - 1), len(order) - 1]))
    print("  names: &[%s]," % ", ".join("(%d, %s)" % (i, q(order[i])) for i in picks))
    kp = []
    kc = 0
    if "kern" in f:
        kt = f["kern"].kernTables[0].kernTable
        kc = sum(len(t.kernTable) for t in f["kern"].kernTables if t.format == 0)
        for (a, b), v in sorted(kt.items())[:: max(1, len(kt) // 40)][:40]:
            kp.append("(%d, %d, %d)" % (gid(a), gid(b), v))
    print("  kern_pairs: &[%s], kern_count: %d }," % (", ".join(kp), kc))
print("];")

# ---- GSUB ligatures and GPOS kern pairs, read through fontTools' object model --------------------------
def lookups_for(t, script, feat):
    out = set()
    srs = {sr.ScriptTag: sr for sr in t.ScriptList.ScriptRecord}
    sr = srs.get(script) or srs.get("DFLT") or srs.get("latn")
    if sr is None or sr.Script.DefaultLangSys is None: return []
    for fi in sr.Script.DefaultLangSys.FeatureIndex:
        fr = t.FeatureList.FeatureRecord[fi]
        if fr.FeatureTag == feat: out.update(fr.Feature.LookupListIndex)
    return sorted(out)

def real_subtables(l):
    for st in l.SubTable:
        if l.LookupType in (7, 9): yield st.ExtSubTable
        else: yield st

print("pub struct Lig { pub lookup: u16, pub first: u16, pub rest: &'static [u16], pub lig: u16 }")
print("pub struct Pair { pub lookup: u16, pub first: u16, pub second: u16, pub x_adv1: i16 }")
print("pub struct LayoutKat { pub path: &'static str, pub liga_lookups: &'static [u16], pub ligs: &'static [Lig], pub kern_lookups: &'static [u16], pub pairs: &'static [Pair] }")
print("pub static LAYOUT_KATS: &[LayoutKat] = &[")
import itertools
for p in FONTS:
    f = TTFont(p); gid = f.getGlyphID
    ligs = []; pairs = []; ll = []; kl = []
    if "GSUB" in f:
        t = f["GSUB"].table
        ll = lookups_for(t, "latn", "liga")
        for li in ll:
            l = t.LookupList.Lookup[li]
            for st in real_subtables(l):
                if not hasattr(st, "ligatures"): continue
                for first, lst in st.ligatures.items():
                    for lg in lst:
                        ligs.append("Lig { lookup: %d, first: %d, rest: &[%s], lig: %d }" % (li, gid(first), ", ".join(str(gid(c)) for c in lg.Component), gid(lg.LigGlyph)))
    if "GPOS" in f:
        t = f["GPOS"].table
        kl = lookups_for(t, "latn", "kern")
        order = f.getGlyphOrder()
        for li in kl:
            l = t.LookupList.Lookup[li]
            sts = [st for st in real_subtables(l) if st.LookupType == 2] if hasattr(l.SubTable[0], "LookupType") else list(real_subtables(l))
            # candidate pairs: sample from each subtable
            cands = []
            for st in sts:
                cov = st.Coverage.glyphs
                if st.Format == 1:
                    for i, ps in enumerate(st.PairSet[::max(1, len(st.PairSet)//6)][:6]):
                        g1 = cov[i * max(1, len(st.PairSet)//6)]
                        for rec in ps.PairValueRecord[:3]: cands.append((g1, rec.SecondGlyph))
                else:
                    c2 = st.ClassDef2.classDefs
                    seconds = sorted(set(c2.keys()))[::max(1, len(c2)//8)][:8] + [order[1]]
                    for g1 in cov[::max(1, len(cov)//6)][:6]:
                        for g2 in seconds: cands.append((g1, g2))
            def resolve(g1, g2):
                for st in sts:
                    if g1 not in st.Coverage.glyphs: continue
                    if st.Format == 1:
                        ps = st.PairSet[st.Coverage.glyphs.index(g1)]
                        for rec in ps.PairValueRecord:
                            if rec.SecondGlyph == g2:
                                v = rec.Value1
                                return getattr(v, "XAdvance", 0) if v else 0
                        continue
                    c1 = st.ClassDef1.classDefs.get(g1, 0); c2 = st.ClassDef2.classDefs.get(g2, 0)
                    v = st.Class1Record[c1].Class2Record[c2].Value1
                    return getattr(v, "XAdvance", 0) if v else 0
                return None
            seen = set()
            for g1, g2 in cands:
                if (g1, g2) in seen: continue
                seen.add((g1, g2))
                v = resolve(g1, g2)
                if v is None: continue
                pairs.append("Pair { lookup: %d, first: %d, second: %d, x_adv1: %d }" % (li, gid(g1), gid(g2), v or 0))
    print("LayoutKat { path: %s, liga_lookups: &[%s], ligs: &[%s], kern_lookups: &[%s], pairs: &[%s] }," % (
        q(p), ", ".join(map(str, ll)), ", ".join(ligs), ", ".join(map(str, kl)), ",\n    ".join(pairs[:60])))
print("];")
