# AETHERFONT (SR61) `name` table KATs: every record fontTools 4.66.1 decodes (toUnicode) for name IDs 1, 2, 4, 6,
# 16, 17 of the container's outline fonts, per face of a collection. Writes tests/data/name_kat.tsv:
#   path \t face \t sha256 \t platformID \t platEncID \t langID \t nameID \t value (\\t \\n escaped)
# Usage: python3 oracle/gen_name_kat.py > tests/data/name_kat.tsv
import glob, hashlib
from fontTools.ttLib import TTFont, TTCollection

PATHS = sorted(glob.glob("/usr/share/fonts/truetype/**/*.tt[fc]", recursive=True)
               + glob.glob("/usr/share/fonts/opentype/**/*.otf", recursive=True))
IDS = {1, 2, 4, 6, 16, 17}
print("# GENERATED by oracle/gen_name_kat.py (fontTools) — path, face, sha256, platform, encoding, language, nameID, value")
for p in PATHS:
    if "NotoColorEmoji" in p:
        continue
    data = open(p, "rb").read()
    sha = hashlib.sha256(data).hexdigest()
    fonts = TTCollection(p).fonts if p.endswith(".ttc") else [TTFont(p)]
    for i, f in enumerate(fonts):
        for n in f["name"].names:
            if n.nameID not in IDS:
                continue
            ok = n.platformID == 0 or (n.platformID == 3 and n.platEncID in (0, 1, 10)) or (n.platformID == 1 and n.platEncID == 0)
            if not ok:
                continue
            try:
                v = n.toUnicode()
            except Exception:
                continue
            v = v.replace("\\", "\\\\").replace("\t", "\\t").replace("\n", "\\n").replace("\r", "\\r")
            print("\t".join([p, str(i), sha, str(n.platformID), str(n.platEncID), str(n.langID), str(n.nameID), v]))
