# FONTBIDI (SR56): generates every Unicode property table font_core uses from the UCD 17.0.0 files — data only.
# Usage: python3 oracle/gen_ucd.py <ucd-dir>      (run from unaos/libs/text/font_core; URLs + sha256 in oracle/vectors.txt)
# Writes src/ucd/{bidi,gc,grapheme,script,norm,joining,indic,linebreak}.rs.
import sys, os, hashlib, re

UCD = sys.argv[1]
OUT = 'src/ucd'
os.makedirs(OUT, exist_ok=True)
MAXCP = 0x10FFFF


def read(name):
    p = os.path.join(UCD, name)
    data = open(p, 'rb').read()
    return data.decode('utf-8'), hashlib.sha256(data).hexdigest()


def rng(s):
    s = s.strip()
    if '..' in s:
        a, b = s.split('..')
        return int(a, 16), int(b, 16)
    return int(s, 16), int(s, 16)


def parse_prop(text, field=1, missing=True, want=None):
    """Return dict cp->value from a `range ; value` file; applies @missing lines (in order) first when asked."""
    out = {}
    defaults = []
    for line in text.splitlines():
        if missing and line.startswith('# @missing:'):
            body = line[len('# @missing:'):].split(';')
            lo, hi = rng(body[0])
            val = body[field].strip()
            if want is not None:
                if body[1].strip() != want:
                    continue
                val = body[2].strip()
            defaults.append((lo, hi, val))
            continue
        line = line.split('#')[0].strip()
        if not line:
            continue
        f = [x.strip() for x in line.split(';')]
        if want is not None:
            if len(f) < 3 or f[1] != want:
                continue
            lo, hi = rng(f[0])
            v = f[2]
        else:
            lo, hi = rng(f[0])
            v = f[field]
        for c in range(lo, hi + 1):
            out[c] = v
    return out, defaults


def full_map(text, default, field=1, want=None):
    vals, defaults = parse_prop(text, field, True, want)
    arr = [default] * (MAXCP + 1)
    for lo, hi, v in defaults:
        if want is None and lo == 0 and hi == MAXCP:
            arr = [v] * (MAXCP + 1)
            continue
        for c in range(lo, hi + 1):
            arr[c] = v
    for c, v in vals.items():
        arr[c] = v
    return arr


def runs(arr, skip=None):
    out = []
    cur = None
    start = 0
    for c in range(MAXCP + 2):
        v = arr[c] if c <= MAXCP else object()
        if v != cur:
            if cur is not None and cur != skip:
                out.append((start, c - 1, cur))
            cur = v
            start = c
    return out


def header(f, title, srcs):
    f.write('//! %s\n//! GENERATED by oracle/gen_ucd.py from the Unicode Character Database 17.0.0 — do not edit by hand.\n' % title)
    for n, sha in srcs:
        f.write('//! %s sha256 %s\n' % (n, sha))
    f.write('\n#![allow(clippy::all)]\n\n')


def write_ranges(f, name, rows, ty, fmt):
    f.write('pub static %s: &[(u32, u32, %s)] = &[\n' % (name, ty))
    for lo, hi, v in rows:
        f.write('    (0x%04X, 0x%04X, %s),\n' % (lo, hi, fmt(v)))
    f.write('];\n\n')


def write_set(f, name, rows):
    f.write('pub static %s: &[(u32, u32)] = &[\n' % name)
    for lo, hi, _ in rows:
        f.write('    (0x%04X, 0x%04X),\n' % (lo, hi))
    f.write('];\n\n')


# ---------------------------------------------------------------- UnicodeData (gc, ccc, decompositions)
ud_text, ud_sha = read('UnicodeData.txt')
gc = ['Cn'] * (MAXCP + 1)
ccc = [0] * (MAXCP + 1)
decomp = {}
names = {}
prev = None
for line in ud_text.splitlines():
    f = line.split(';')
    cp = int(f[0], 16)
    if f[1].endswith(', Last>'):
        for c in range(prev + 1, cp + 1):
            gc[c] = f[2]
            ccc[c] = int(f[3])
    gc[cp] = f[2]
    ccc[cp] = int(f[3])
    if f[5] and not f[5].startswith('<'):
        decomp[cp] = [int(x, 16) for x in f[5].split()]
    prev = cp

GC_NAMES = ['Lu', 'Ll', 'Lt', 'Lm', 'Lo', 'Mn', 'Mc', 'Me', 'Nd', 'Nl', 'No', 'Pc', 'Pd', 'Ps', 'Pe', 'Pi', 'Pf', 'Po',
            'Sm', 'Sc', 'Sk', 'So', 'Zs', 'Zl', 'Zp', 'Cc', 'Cf', 'Cs', 'Co', 'Cn']
dcp_text0, dcp_sha0 = read('DerivedCoreProperties.txt')
dicp = [False] * (MAXCP + 1)
for line in dcp_text0.splitlines():
    line = line.split('#')[0].strip()
    if not line:
        continue
    f_ = [x.strip() for x in line.split(';')]
    if len(f_) == 2 and f_[1] == 'Default_Ignorable_Code_Point':
        lo, hi = rng(f_[0])
        for c in range(lo, hi + 1):
            dicp[c] = True
with open(os.path.join(OUT, 'gc.rs'), 'w') as f:
    header(f, 'General_Category (UnicodeData.txt field 2; unlisted = Cn) and Default_Ignorable_Code_Point.',
           [('UnicodeData.txt', ud_sha), ('DerivedCoreProperties.txt', dcp_sha0)])
    f.write('use super::Gc;\n\n')
    write_ranges(f, 'GC', runs(gc, skip='Cn'), 'Gc', lambda v: 'Gc::' + v)
    write_set(f, 'DEFAULT_IGNORABLE', runs(dicp, skip=False))

# ---------------------------------------------------------------- Bidi
bc_text, bc_sha = read('DerivedBidiClass.txt')
pva_text, pva_sha = read('PropertyValueAliases.txt')
long2short = {}
sc_alias = {}
for line in pva_text.splitlines():
    line = line.split('#')[0].strip()
    if not line:
        continue
    f = [x.strip() for x in line.split(';')]
    if f[0] == 'bc':
        long2short[f[2]] = f[1]
    if f[0] == 'sc':
        sc_alias[f[2]] = f[1]
        for extra in f[3:]:
            sc_alias[extra] = f[1]
bc = full_map(bc_text, 'L')
bc = [long2short.get(v, v) for v in bc]
br_text, br_sha = read('BidiBrackets.txt')
mi_text, mi_sha = read('BidiMirroring.txt')
brackets = []
for line in br_text.splitlines():
    line = line.split('#')[0].strip()
    if not line:
        continue
    a, b, t = [x.strip() for x in line.split(';')]
    brackets.append((int(a, 16), int(b, 16), t == 'o'))
mirrors = []
for line in mi_text.splitlines():
    line = line.split('#')[0].strip()
    if not line:
        continue
    a, b = [x.strip() for x in line.split(';')]
    mirrors.append((int(a, 16), int(b, 16)))
with open(os.path.join(OUT, 'bidi.rs'), 'w') as f:
    header(f, 'Bidi_Class (DerivedBidiClass.txt incl. @missing defaults), Bidi_Mirroring_Glyph, Bidi_Paired_Bracket(_Type).',
           [('extracted/DerivedBidiClass.txt', bc_sha), ('BidiMirroring.txt', mi_sha), ('BidiBrackets.txt', br_sha)])
    f.write('use crate::bidi::BidiClass;\n\n')
    write_ranges(f, 'BIDI_CLASS', runs(bc, skip='L'), 'BidiClass', lambda v: 'BidiClass::' + v)
    f.write('/// (code point, Bidi_Mirroring_Glyph), sorted.\npub static MIRROR: &[(u32, u32)] = &[\n')
    for a, b in sorted(mirrors):
        f.write('    (0x%04X, 0x%04X),\n' % (a, b))
    f.write('];\n\n/// (code point, Bidi_Paired_Bracket, is opening), sorted.\npub static BRACKETS: &[(u32, u32, bool)] = &[\n')
    for a, b, o in sorted(brackets):
        f.write('    (0x%04X, 0x%04X, %s),\n' % (a, b, 'true' if o else 'false'))
    f.write('];\n')

# ---------------------------------------------------------------- Graphemes (GCB, Extended_Pictographic, InCB)
gb_text, gb_sha = read('GraphemeBreakProperty.txt')
gcb = full_map(gb_text, 'Other')
em_text, em_sha = read('emoji-data.txt')
ext_pict = [False] * (MAXCP + 1)
for line in em_text.splitlines():
    line = line.split('#')[0].strip()
    if not line:
        continue
    a, p = [x.strip() for x in line.split(';')]
    if p == 'Extended_Pictographic':
        lo, hi = rng(a)
        for c in range(lo, hi + 1):
            ext_pict[c] = True
dcp_text, dcp_sha = read('DerivedCoreProperties.txt')
incb = ['None'] * (MAXCP + 1)
for line in dcp_text.splitlines():
    line = line.split('#')[0].strip()
    if not line:
        continue
    f = [x.strip() for x in line.split(';')]
    if len(f) == 3 and f[1] == 'InCB':
        lo, hi = rng(f[0])
        for c in range(lo, hi + 1):
            incb[c] = f[2]
with open(os.path.join(OUT, 'grapheme.rs'), 'w') as f:
    header(f, 'Grapheme_Cluster_Break, Extended_Pictographic, Indic_Conjunct_Break (UAX #29).',
           [('auxiliary/GraphemeBreakProperty.txt', gb_sha), ('emoji/emoji-data.txt', em_sha), ('DerivedCoreProperties.txt', dcp_sha)])
    f.write('use super::{Gcb, InCb};\n\n')
    write_ranges(f, 'GCB', runs(gcb, skip='Other'), 'Gcb', lambda v: 'Gcb::' + v)
    write_set(f, 'EXT_PICT', runs(ext_pict, skip=False))
    write_ranges(f, 'INCB', runs(incb, skip='None'), 'InCb', lambda v: 'InCb::' + v)

# ---------------------------------------------------------------- Scripts + Script_Extensions
sc_text, sc_sha = read('Scripts.txt')
scx_text, scx_sha = read('ScriptExtensions.txt')
sc = full_map(sc_text, 'Unknown')
sc = [sc_alias.get(v, v) for v in sc]
scripts = sorted(set(sc_alias.values()))
# Zyyy (Common), Zinh (Inherited), Zzzz (Unknown) first so their codes are stable.
for s in ['Zyyy', 'Zinh', 'Zzzz']:
    scripts.remove(s)
    scripts.insert(0, s)
sidx = {s: i for i, s in enumerate(scripts)}
scx = {}
for line in scx_text.splitlines():
    line = line.split('#')[0].strip()
    if not line:
        continue
    a, v = [x.strip() for x in line.split(';')]
    lo, hi = rng(a)
    for c in range(lo, hi + 1):
        scx[c] = tuple(sorted(sidx[sc_alias.get(x, x)] for x in v.split()))
sets = sorted(set(scx.values()))
setidx = {s: i for i, s in enumerate(sets)}
scx_arr = [None] * (MAXCP + 1)
for c, s in scx.items():
    scx_arr[c] = setidx[s]
with open(os.path.join(OUT, 'script.rs'), 'w') as f:
    header(f, 'Script (Scripts.txt) and Script_Extensions (ScriptExtensions.txt), ISO 15924 codes from PropertyValueAliases.txt.',
           [('Scripts.txt', sc_sha), ('ScriptExtensions.txt', scx_sha), ('PropertyValueAliases.txt', pva_sha)])
    f.write('/// ISO 15924 codes indexed by script id (0 = Zzzz Unknown, 1 = Zinh Inherited, 2 = Zyyy Common).\n')
    f.write('pub static SCRIPT_CODES: &[[u8; 4]] = &[\n')
    for s in scripts:
        f.write('    *b"%s",\n' % s)
    f.write('];\n\n')
    write_ranges(f, 'SCRIPT', runs([sidx[v] for v in sc], skip=0), 'u8', str)
    write_ranges(f, 'SCRIPT_EXT', runs(scx_arr, skip=None), 'u16', str)
    f.write('/// Script_Extensions sets (script ids), indexed by SCRIPT_EXT values.\npub static SCX_SETS: &[&[u8]] = &[\n')
    for s in sets:
        f.write('    &[%s],\n' % ', '.join(str(x) for x in s))
    f.write('];\n')

# ---------------------------------------------------------------- Normalization (UAX #15)
dn_text, dn_sha = read('DerivedNormalizationProps.txt')
excl = set()
for line in dn_text.splitlines():
    line = line.split('#')[0].strip()
    if not line:
        continue
    f = [x.strip() for x in line.split(';')]
    if len(f) == 2 and f[1] == 'Full_Composition_Exclusion':
        lo, hi = rng(f[0])
        excl.update(range(lo, hi + 1))
comp = []
for cp, d in decomp.items():
    if len(d) == 2 and cp not in excl:
        comp.append((d[0], d[1], cp))
with open(os.path.join(OUT, 'norm.rs'), 'w') as f:
    header(f, 'Canonical_Combining_Class, canonical Decomposition_Mapping (one level; Hangul is algorithmic) and the primary '
              'composites (two-code-point canonical decompositions minus Full_Composition_Exclusion).',
           [('UnicodeData.txt', ud_sha), ('DerivedNormalizationProps.txt', dn_sha)])
    write_ranges(f, 'CCC', runs(ccc, skip=0), 'u8', str)
    data = []
    rows = []
    for cp in sorted(decomp):
        rows.append((cp, len(data), len(decomp[cp])))
        data.extend(decomp[cp])
    f.write('/// (code point, start, len) into DECOMP_DATA, sorted.\npub static DECOMP: &[(u32, u16, u8)] = &[\n')
    for cp, s, n in rows:
        f.write('    (0x%04X, %d, %d),\n' % (cp, s, n))
    f.write('];\n\npub static DECOMP_DATA: &[u32] = &[\n')
    for i in range(0, len(data), 12):
        f.write('    ' + ', '.join('0x%04X' % x for x in data[i:i + 12]) + ',\n')
    f.write('];\n\n/// (first, second, composite), sorted by (first, second).\npub static COMPOSE: &[(u32, u32, u32)] = &[\n')
    for a, b, c in sorted(comp):
        f.write('    (0x%04X, 0x%04X, 0x%04X),\n' % (a, b, c))
    f.write('];\n')

# ---------------------------------------------------------------- Arabic joining (ArabicShaping.txt)
as_text, as_sha = read('ArabicShaping.txt')
jt = ['U'] * (MAXCP + 1)
for c in range(MAXCP + 1):
    if gc[c] in ('Mn', 'Me', 'Cf'):
        jt[c] = 'T'  # ArabicShaping.txt header: unlisted Mn, Me and Cf are Transparent
jg = {}
for line in as_text.splitlines():
    line = line.split('#')[0].strip()
    if not line:
        continue
    f = [x.strip() for x in line.split(';')]
    cp = int(f[0], 16)
    jt[cp] = f[2]
    jg[cp] = f[3]
with open(os.path.join(OUT, 'joining.rs'), 'w') as f:
    header(f, 'Joining_Type (ArabicShaping.txt; unlisted Mn/Me/Cf are T, the rest U).', [('ArabicShaping.txt', as_sha), ('UnicodeData.txt', ud_sha)])
    f.write('use super::Jt;\n\n')
    write_ranges(f, 'JOINING', runs(jt, skip='U'), 'Jt', lambda v: 'Jt::' + v)

# ---------------------------------------------------------------- Indic categories (USE / Indic shaping)
isc_text, isc_sha = read('IndicSyllabicCategory.txt')
ipc_text, ipc_sha = read('IndicPositionalCategory.txt')
isc = full_map(isc_text, 'Other')
ipc = full_map(ipc_text, 'Not_Applicable')
with open(os.path.join(OUT, 'indic.rs'), 'w') as f:
    header(f, 'Indic_Syllabic_Category and Indic_Positional_Category.', [('IndicSyllabicCategory.txt', isc_sha), ('IndicPositionalCategory.txt', ipc_sha)])
    f.write('use super::{Isc, Ipc};\n\n')
    write_ranges(f, 'ISC', runs(isc, skip='Other'), 'Isc', lambda v: 'Isc::' + v)
    write_ranges(f, 'IPC', runs(ipc, skip='Not_Applicable'), 'Ipc', lambda v: 'Ipc::' + v)

# ---------------------------------------------------------------- Line breaking (UAX #14)
lb_text, lb_sha = read('LineBreak.txt')
ea_text, ea_sha = read('EastAsianWidth.txt')
lb = full_map(lb_text, 'XX')
ea = full_map(ea_text, 'N')
with open(os.path.join(OUT, 'linebreak.rs'), 'w') as f:
    header(f, 'Line_Break (LineBreak.txt) and the East_Asian_Width F/W/H set UAX #14 LB19a/LB30 need.',
           [('LineBreak.txt', lb_sha), ('EastAsianWidth.txt', ea_sha)])
    f.write('use crate::linebreak::Lb;\n\n')
    write_ranges(f, 'LINE_BREAK', runs(lb, skip='XX'), 'Lb', lambda v: 'Lb::' + v)
    write_set(f, 'EAST_ASIAN_FWH', runs([v in ('F', 'W', 'H') for v in ea], skip=False))

# ---------------------------------------------------------------- Indic vowel constraints (Microsoft data)
vc_text, vc_sha = read('IndicShapingInvalidCluster.txt')
seqs = []
for line in vc_text.splitlines():
    line = line.split('#')[0].split(';')[0].strip()
    if line:
        seqs.append([int(x, 16) for x in line.split()])
with open(os.path.join(OUT, 'vowel_constraints.rs'), 'w') as f:
    f.write('//! Indic_Shaping_Invalid_Cluster sequences (independent vowel + matra look-alikes): a dotted circle is inserted\n')
    f.write('//! before the last character. GENERATED by oracle/gen_ucd.py from Microsoft\'s IndicShapingInvalidCluster.txt\n')
    f.write('//! (the file shaping engines use) sha256 %s — do not edit by hand.\n\n' % vc_sha)
    f.write('pub static INVALID_CLUSTERS: &[&[u32]] = &[\n')
    for q in sorted(seqs):
        f.write('    &[%s],\n' % ', '.join('0x%04X' % c for c in q))
    f.write('];\n')

print('ok: gc/bidi/grapheme/script/norm/joining/indic/linebreak; %d scripts, %d scx sets, %d composites' % (len(scripts), len(sets), len(comp)), file=sys.stderr)
print('enums:', file=sys.stderr)
print(' bc', sorted(set(bc)), file=sys.stderr)
print(' gcb', sorted(set(gcb)), file=sys.stderr)
print(' incb', sorted(set(incb)), file=sys.stderr)
print(' jt', sorted(set(jt)), file=sys.stderr)
print(' isc', sorted(set(isc)), file=sys.stderr)
print(' ipc', sorted(set(ipc)), file=sys.stderr)
print(' lb', sorted(set(lb)), file=sys.stderr)
