# Generates src/linebreak/table.rs from LineBreak-17.0.0.txt for the FONTCORE supported ranges.
# Usage: python3 oracle/gen_lb.py LineBreak.txt src/linebreak/table.rs  (source URL + sha256: oracle/vectors.txt)
import sys, re, hashlib
src = sys.argv[1]
data = open(src,'rb').read()
sha = hashlib.sha256(data).hexdigest()
RANGES = [(0x0000,0x052F),(0x1C80,0x1C8F),(0x1D00,0x1DFF),(0x1E00,0x1FFF),(0x2000,0x206F),(0x20A0,0x20A8),(0x20AA,0x20C1),(0x2DE0,0x2DFF),(0xA640,0xA69F),(0xA720,0xA7FF),(0xFB00,0xFB06),(0xFEFF,0xFEFF)]
cls = {}
for line in data.decode().splitlines():
    line=line.split('#')[0].strip()
    if not line: continue
    a,b=[x.strip() for x in line.split(';')]
    if '..' in a: lo,hi=[int(x,16) for x in a.split('..')]
    else: lo=hi=int(a,16)
    for c in range(lo,hi+1): cls[c]=b
def resolve(c):
    k = cls.get(c,'XX')
    return k
rows=[]
for lo,hi in RANGES:
    cur=None; start=lo
    for c in range(lo,hi+2):
        k = resolve(c) if c<=hi else None
        if k!=cur:
            if cur is not None: rows.append((start,c-1,cur))
            cur=k; start=c
used=sorted(set(r[2] for r in rows))
out=[]
out.append('//! UAX #14 Line_Break classes for the FONTCORE ranges (Latin, IPA, Greek, Cyrillic, general punctuation,')
out.append('//! currency, Latin ligatures). GENERATED by oracle/gen_lb.py from LineBreak-17.0.0.txt,')
out.append('//! sha256 %s — do not edit by hand.' % sha)
out.append('')
out.append('use super::Lb;')
out.append('')
out.append('/// The supported code point ranges: inside them `class()` is exact, outside it answers `XX`.')
out.append('pub static RANGES: &[(u32, u32)] = &[')
for lo,hi in RANGES: out.append('    (0x%04X, 0x%04X),' % (lo,hi))
out.append('];')
out.append('')
out.append('/// (first, last, class), sorted, non-overlapping.')
out.append('pub static TABLE: &[(u32, u32, Lb)] = &[')
for lo,hi,k in rows: out.append('    (0x%04X, 0x%04X, Lb::%s),' % (lo,hi,k))
out.append('];')
open(sys.argv[2],'w').write('\n'.join(out)+'\n')
print(len(rows), used, file=sys.stderr)
