#!/usr/bin/env python3
"""HTMLCORE (SR46): generate src/entities.rs from the WHATWG named character reference table.

Usage: python3 tools/gen_entities.py entities.json > src/entities.rs

entities.json is the spec's JSON form of §13.5 "Named character references" (2231 names; the list is
frozen by the spec: "This list is static and will not be expanded or changed in the future"). The URL and
sha256 used are in vectors.txt. The output is DATA ONLY: a sorted table of (name-without-&, replacement).
"""
import json, sys, hashlib

raw = open(sys.argv[1], 'rb').read()
d = json.loads(raw)
rows = sorted(((k[1:], v["characters"]) for k, v in d.items()), key=lambda r: r[0].encode())

def lit(s):
    out = []
    for ch in s:
        o = ord(ch)
        if ch.isascii() and (ch.isalnum() or ch in " !#$%&()*+,-./:;<=>?@[]^_`{|}~'"):
            out.append(ch)
        else:
            out.append("\\u{%x}" % o)
    return '"' + "".join(out) + '"'

print("// @generated by tools/gen_entities.py from the WHATWG entities.json — DATA ONLY, do not edit.")
print("// source sha256 %s, %d names (see vectors.txt)." % (hashlib.sha256(raw).hexdigest(), len(rows)))
print("//")
print("// Sorted by the byte order of the name (without the leading '&'), so the tokenizer can narrow a")
print("// prefix range one character at a time (§13.2.5.73 named character reference state).")
print()
print("/// `(name without the leading '&', replacement characters)`, sorted by name.")
print("pub static ENTITIES: &[(&str, &str)] = &[")
for k, v in rows:
    print("    (%s, %s)," % (lit(k), lit(v)))
print("];")
